import React from 'react';
import { Language } from '../types';

interface AboutUnawatunaProps {
  language: Language;
}

const AboutUnawatuna: React.FC<AboutUnawatunaProps> = ({ language }) => {
  const content = {
    title: language === 'EN' ? "Complete Travel Guide — Unawatuna" : "සම්පූර්ණ සංචාරක මාර්ගෝපදේශය — උණවටුන",
    subtitle: language === 'EN' ? "Sri Lanka's Beloved Bay — Where the Southern Coast Comes Alive" : "ශ්‍රී ලංකාවේ ආදරණීය බොක්ක — දකුණු වෙරළ තීරය ජීවමාන වන ස්ථානය",
    description: language === 'EN' ? "Galle District, Southern Province • Beach destination • Open year-round • 5 km from Galle Fort" : "ගාල්ල දිස්ත්‍රික්කය, දකුණු පළාත • වෙරළ ගමනාන්තය • වසර පුරා විවෘතයි • ගාලු කොටුවේ සිට කි.මී. 5 යි",
    sections: [
      {
        title: language === 'EN' ? "Section 01: Introduction — Why Unawatuna Matters" : "01 වන කොටස: හැඳින්වීම — උණවටුන වැදගත් වන්නේ ඇයි",
        body: "Unawatuna is, by almost any measure, the most famous beach on Sri Lanka's southern coast. Nestled inside a wide, sheltered bay roughly five kilometres southeast of the historic Galle Fort, it has drawn travellers for decades with a combination of qualities that are genuinely rare to find together in a single place: calm, swimmable water protected by a natural reef, a crescent of golden sand fringed by coconut palms, a lively strip of restaurants and guesthouses within walking distance of the shore, and easy access to some of the south's most compelling cultural and natural attractions.\n\nThe beach itself is compact enough to feel intimate and unhurried, yet developed enough to offer every comfort a traveller might need. It is a place where a honeymooning couple, a solo backpacker, a family with young children, and a seasoned diver can all find exactly what they are looking for within a few hundred metres of each other. This combination of accessibility and beauty is what has made Unawatuna not just a popular stop on the southern circuit but for many visitors the centrepiece of their entire Sri Lanka trip.\n\nDespite its popularity, Unawatuna has retained much of its village character. The streets behind the beach are narrow and shaded, lined with small family-run guesthouses, local cafes, and the occasional stray cat. The pace of life here slows noticeably the moment you arrive, and the rhythms of the place — the morning light on the water, the sound of fishing boats heading out before dawn, the cool of the evening when the beach restaurants fill with the smell of grilled fish — have a way of making even the most schedule-driven traveller want to stay longer than planned."
      },
      {
        title: language === 'EN' ? "Section 02: History — From Fishing Village to Famous Shore" : "02 වන කොටස: ඉතිහාසය — ධීවර ගම්මානයේ සිට ප්‍රසිද්ධ වෙරළ තීරය දක්වා",
        body: "For most of its history, Unawatuna was simply a small coastal fishing community on the southwestern edge of the Galle peninsula. The bay's naturally sheltered position — created by a headland to the west and a reef system offshore — made it ideal for small-scale fishing, and for centuries the village existed quietly in the shadow of the far more historically significant Galle, just a few kilometres away. The Portuguese, Dutch, and British colonial powers who successively controlled Galle and its famous fort had little particular interest in Unawatuna itself, and the village remained largely undisturbed.\n\nIt was not until the latter decades of the 20th century that travellers — initially the independent backpacker community that was then discovering the charms of Sri Lanka's southern coast — began stopping at Unawatuna in significant numbers. The bay's calm, reef-protected waters, which made it safe for swimming even when nearby beaches were rougher, and its picture-perfect crescent shape made it an instant favourite. Small guesthouses and beach restaurants began to appear along the shore, and by the 1990s Unawatuna had earned a devoted following.\n\nThe 2004 Indian Ocean tsunami hit the southern coast of Sri Lanka with devastating force, and Unawatuna suffered significant damage. Many of the beachfront structures were destroyed or heavily damaged, and the community endured a period of profound hardship and rebuilding. Within a few years, however, the village had recovered and the tourism industry along the bay had returned — and in many ways emerged more organised and better developed than before. The tsunami also prompted environmental reflection, and awareness of the need to protect the reef system and coastal vegetation has been higher in Unawatuna since then than it was in earlier decades of development.\n\n\"Unawatuna's bay was shaped by the sea over millennia — the reef that makes it calm enough to swim in is the same reef that has defined the character of this place for centuries.\""
      },
      {
        title: language === 'EN' ? "Section 03: The Beach — Understanding the Bay" : "03 වන කොටස: වෙරළ — බොක්ක අවබෝධ කර ගැනීම",
        body: "The beach at Unawatuna runs for approximately 800 metres in a gentle crescent arc, bounded at its western end by a rocky headland and at its eastern end by a second promontory that shelters the bay from the open ocean. This natural geography is fundamental to what makes Unawatuna special. The offshore reef system breaks the force of the Indian Ocean swell before it reaches the shore, producing calm, clear water that is safe for swimming for most of the year. The bay floor shelves gently, making it excellent for families with children and for less confident swimmers who might struggle on more exposed southern beaches.\n\nThe sand is golden and relatively coarse, typical of Sri Lanka's southern coast. At low tide the beach is wide and spacious; at high tide it narrows considerably in some sections, particularly toward the western end near the main restaurant strip. The water colour varies from a vivid turquoise in the shallows to a deeper blue-green further out, and on a clear day the contrast with the white sand and green palm fringe above is genuinely postcard-perfect.\n\nThe western section of the beach, closest to the main road and the cluster of larger restaurants and beach bars, is busiest and most developed. The eastern section, curving away toward the far headland, is quieter and more sheltered. A short walk around the eastern headland brings you to Jungle Beach — a smaller, wilder, and far less visited cove that has no commercial development and is beloved by those who know about it. Reaching it requires either a short scramble over the rocks or a five-minute walk through the jungle, which is part of what keeps it blissfully uncrowded."
      },
      {
        title: language === 'EN' ? "Section 04: Snorkelling and Diving — The Underwater World" : "04 වන කොටස: ස්නෝකර්ලිං සහ කිමිදීම — දිය යට ලෝකය",
        body: "The reef system at Unawatuna is one of the bay's greatest assets and one of the primary reasons serious water sports enthusiasts make the journey here. The reef begins relatively close to shore — in some sections just 50 to 100 metres from the beach — making snorkelling accessible even for beginners. The coral garden in the central and eastern sections of the bay supports a rich population of reef fish including parrotfish, pufferfish, trumpetfish, moray eels, and on fortunate days, sea turtles. The turtles in particular are a beloved presence at Unawatuna and sightings are surprisingly common for those who spend enough time in the water.\n\nFor scuba divers, several dive sites are accessible from Unawatuna within a short boat ride. The most famous is the Rangoon Wreck — the remains of a British cargo ship that sank in 1863 and now sits at a depth of approximately 15 to 30 metres off the Galle coast. The wreck is encrusted with coral and home to a diverse range of marine life. It is suitable for intermediate to advanced divers and is considered one of the most interesting wreck dives on Sri Lanka's southern coast. Other nearby sites include Cathedral Rock, a dramatic underwater rock formation, and various reef systems further offshore.\n\nMultiple dive operators are based in and around Unawatuna, offering everything from beginner courses to technical diving and underwater photography guidance. Standards are generally good, particularly among the longer-established operators, though as with any diving destination it is worth checking certifications and equipment before booking. The best diving conditions at Unawatuna coincide with the dry season on the southern coast — roughly November through April — when visibility is at its clearest and the sea is most settled.\n\nReef care reminder\nThe Unawatuna reef has suffered bleaching events and damage from tourism pressure over the years. Never stand on coral, avoid wearing sunscreen before entering the water (use reef-safe alternatives), and do not feed or chase marine life including sea turtles.\n\nIf you snorkel, fins are strongly recommended — they prevent the accidental kicking of coral that occurs when swimmers without fins try to stabilise themselves in the water."
      },
      {
        title: language === 'EN' ? "Section 05: Food and Drink — Eating Well on the Southern Shore" : "05 වන කොටස: ආහාර සහ පාන වර්ග — දකුණු වෙරළේ හොඳින් ආහාර ගැනීම",
        body: "Unawatuna has a genuinely excellent food scene for a beach village of its size. The main strip of restaurants runs immediately behind and alongside the western end of the beach, and the concentration of good options within a short walk of the shore is impressive. The dominant cuisine is, of course, Sri Lankan seafood — freshly caught fish, prawns, crab, and squid prepared in a range of styles from simple grilled preparations to rich coconut curries and devilled dishes fragrant with Sri Lankan spice blends. Eating fresh tuna or barracuda grilled over charcoal on a beachside terrace as the sun goes down is one of the defining pleasures of any visit to Unawatuna.\n\nBeyond seafood, the village caters to a wide range of palates. Italian restaurants, many of them longstanding and well-regarded, have been a feature of the Unawatuna dining scene for years and reflect the significant European traveller base the village attracts. You will also find excellent rice and curry at local family-run spots away from the beach strip — smaller, quieter, and considerably cheaper than the beachfront restaurants, with the kind of home-style cooking that is often far more satisfying than anything prepared for tourist consumption. Sri Lankan breakfast staples like hoppers, kottuস্বপ roti, and string hoppers are available at multiple spots in the village and are a morning ritual worth adopting.\n\nThe beach bars along the shore serve cold beer, fresh coconut water, fruit juices, and a range of cocktails. Arrack — Sri Lanka's distinctive coconut spirit — features prominently and pairs surprisingly well with a lime soda and a seat facing the water. Several of the beach restaurants set up low tables and cushions directly on the sand in the evenings, creating an atmosphere that is relaxed and sociable without being loud or intrusive. By ten o'clock in the evening most of the village quietens down considerably, which is either a relief or a disappointment depending on what you came for."
      },
      {
        title: language === 'EN' ? "Section 06: Where to Stay — Accommodation for Every Traveller" : "06 වන කොටස: නවාතැන් — සෑම සංචාරකයෙකුටම නවාතැන්",
        body: "Unawatuna offers accommodation across a broad range of styles and budgets, from simple fan-cooled guesthouses in family homes a short walk from the beach to polished boutique hotels with rooftop pools and sea views. The concentration of options is high relative to the size of the village, which means that even in peak season there is generally something available for most travellers, though advance booking is strongly advisable from December through March and over the Sri Lankan holiday periods.\n\nThe most desirable — and consequently the most expensive — accommodation is beachfront or beach-adjacent, where the sound of the waves and the proximity to the sand justify the premium. These properties range from well-run mid-range guesthouses with air-conditioned rooms and garden restaurants to small boutique hotels that have invested in design, comfort, and service to a degree that makes them genuinely competitive with international standards. Several of the better boutique options in Unawatuna have become destinations in their own right, with guests choosing the village specifically because of the hotel they want to stay in.\n\nBudget travellers are well catered for in the lanes behind the beach, where smaller guesthouses and homestays offer simple, clean rooms at very reasonable rates. These properties often have the advantage of being embedded in the village itself — closer to the local cafes, the market, and the rhythms of everyday life — which for many travellers is a more rewarding experience than the beach strip. Wherever you stay, it is worth noting that Unawatuna village is small enough to be entirely navigable on foot, which means location is less critical here than in larger tourist destinations."
      },
      {
        title: language === 'EN' ? "Section 07: Galle Fort — The Essential Day Trip" : "07 වන කොටස: ගාලු කොටුව — අත්‍යවශ්‍ය දෛනික සංචාරය",
        body: "No visit to Unawatuna is complete without spending significant time at Galle Fort, located just five kilometres to the west along the coast road. The fort is one of the finest and best-preserved examples of European colonial fortification in Asia, and the UNESCO-listed old town it encloses is one of the most atmospheric and walkable urban spaces in all of Sri Lanka. The relationship between Unawatuna and Galle Fort is symbiotic — many visitors use Unawatuna as their base and make daily visits to the fort, while others stay within the fort's walls and make the short journey down to Unawatuna for beach days.\n\nBuilt by the Portuguese in 1588 and extensively redesigned by the Dutch in the 17th century, the fort's massive bastion walls enclose a grid of old streets lined with colonial-era buildings that have been gradually converted into boutique hotels, independent cafes, galleries, jewellery shops, and restaurants. Walking these streets in the early morning or late afternoon, when the light falls at a low angle across the old stone buildings and the ramparts are quiet, is a genuinely beautiful experience. The fort walls themselves can be walked in their entirety — a circuit of approximately two kilometres that offers views in one direction over the old town and in the other over the open Indian Ocean.\n\nThe fort is home to a lighthouse, a Dutch Reformed church dating to 1755, several mosques, a national museum, and a range of historical monuments. But it is the living quality of the place — the fact that people actually live and work inside these ancient walls, that the streets smell of spice and coffee and salt air, that cats sleep in doorways and children play in courtyards — that elevates it beyond mere monument status. A tuk-tuk between Unawatuna and Galle Fort takes around ten minutes and costs very little."
      },
      {
        title: language === 'EN' ? "Section 08: Practical Information — What You Need to Know" : "08 වන කොටස: ප්‍රායෝගික තොරතුරු — ඔබ දැනගත යුතු දේ",
        body: "Location: 5 km from Galle\nDistance from Colombo: ~125 km (2–3 hrs)\nBeach entry: Free, open 24 hrs\nBest swimming season: Nov – April\nWater temperature: 26 – 29°C year-round\nNearest hospital: Galle Teaching Hospital\n\nThe beach at Unawatuna has no entrance fee and is freely accessible at all hours. The road that runs parallel to the beach is a public thoroughfare, and the beach itself is a public space, though many of the sun loungers and umbrellas along the shore belong to specific restaurants and come with the expectation of purchasing food or drinks. If you simply want to sit on the open sand without any obligation, move toward the eastern section of the bay, which is less commercially developed.\n\nSri Lankan rupees are the local currency and while many restaurants and guesthouses accept cards, cash is more reliable, particularly at smaller establishments and market vendors. A reliable ATM is available in the village and in Galle town. Mobile connectivity is generally good with major Sri Lankan networks covering the area. The beach road can become congested with tuk-tuks and motorcycles during busy periods, but the village itself remains perfectly walkable at all times.\n\nVisitor tips:\nThe ocean at Unawatuna is generally calm but currents can develop, particularly around the headlands. Always swim within the designated areas and pay attention to any warning flags.\n\nDress modestly when walking through the village away from the beach. Swimwear is appropriate on the sand but not in shops, restaurants set back from the shore, or places of worship.\n\nEarly morning is the best time to have the beach largely to yourself — the light is beautiful and the water is at its calmest before the sea breeze picks up.\n\nTuk-tuk drivers at Unawatuna are generally reliable for short local trips. Agree on the fare before you get in, or use a ride-hailing app for greater price certainty."
      },
      {
        title: language === 'EN' ? "Section 09: Best Time to Visit — Season and Sea" : "09 වන කොටස: සංචාරය කිරීමට හොඳම කාලය — කාලගුණය සහ මුහුද",
        body: "Unawatuna sits on Sri Lanka's southwestern coast, which means its seasons are governed by the southwest monsoon. The dry season on this coast runs from approximately November through April, and this is the period when conditions at Unawatuna are at their most reliably beautiful. The sea is calm and clear, the skies are predominantly blue, and the beach is at its most inviting. December and January in particular are excellent months — warm, dry, and brilliant — though they are also the busiest, with significant numbers of European visitors escaping their winter. Advance bookings for accommodation and popular restaurants during this window are strongly advised.\n\nThe southwest monsoon arrives on the southern coast sometime between May and June and brings with it significant rainfall and rougher seas. Swimming at Unawatuna during the monsoon months — roughly May through September — requires caution. The bay's reef still provides some protection from the worst of the swell, but the sea can be considerably rougher than during the dry season, particularly in June and July. The upside of visiting during this period is that the village is dramatically quieter, accommodation is cheaper, and the landscape turns an intense, saturated green as the rain moves through.\n\nOctober and November represent a transition period when the monsoon is retreating and conditions at Unawatuna are generally improving. These months can be unpredictable — clear sunny days followed by sudden heavy showers — but they are also among the most atmospheric times to visit, when the village is uncrowded, prices are reasonable, and the light in the late afternoon has a quality that is impossible to photograph but impossible to forget once you have seen it. For travellers with flexible itineraries, the shoulder months of October to November and late April to May offer an appealing middle ground between peak-season crowds and monsoon conditions."
      },
      {
        title: language === 'EN' ? "Section 10: Getting There — Reaching Unawatuna" : "10 වන කොටස: ගමන් මාර්ගය — උණවටුනට ළඟා වීම",
        body: "Unawatuna is one of the more accessible beach destinations on Sri Lanka's southern coast, benefiting from its proximity to Galle, which is itself well connected to Colombo by both road and rail. The most scenic and enjoyable way to arrive from Colombo is by train — the Coastal Line runs along the southern coast and the journey between Colombo Fort and Galle takes approximately two to two-and-a-half hours, passing through Bentota, Hikkaduwa, and several other coastal towns. The train hugs the coast in sections, offering views of lagoons, beaches, and small fishing villages. From Galle station, Unawatuna is a ten-minute tuk-tuk ride south along the coast road.\n\nBy road from Colombo, the Southern Expressway provides a fast and comfortable connection to Galle, reducing the journey to around an hour and a half by private car or highway bus. From the Galle exit, Unawatuna is a further fifteen minutes along the old coast road. If you are travelling from the airport at Colombo, pre-arranged airport transfers directly to Unawatuna can be organised through most guesthouses and tour operators, with the journey taking approximately two to three hours depending on traffic, which can be heavy on the approach to Colombo itself.\n\nUnawatuna is also well positioned as a stop on a broader southern coast itinerary. Mirissa — famous for whale watching and its own excellent beach — is located approximately 25 kilometres to the east and makes a natural next destination. Weligama, renowned for surf breaks and a distinctly laid-back character, is between the two. Travelling eastward along the coast from Unawatuna, either by tuk-tuk, bus, or hired car, allows you to trace the full length of the southern coast at whatever pace suits you, stopping wherever the view or the restaurant sign catches your eye."
      },
      {
        title: language === 'EN' ? "Section 11: Nearby Attractions — Beyond the Beach" : "11 වන කොටස: අවට ආකර්ෂණීය ස්ථාන — වෙරළෙන් ඔබ්බට",
        body: "Immediately west of Unawatuna, the Japanese Peace Pagoda sits atop a forested headland above the bay, accessible via a short but steep path through the jungle from the western end of the beach. Built by Japanese Buddhist monks and completed in 2005, the white stupa sits in near silence above the treetops with sweeping views over Unawatuna bay below and the open ocean beyond. The walk up takes roughly fifteen minutes and the site is open to visitors of all backgrounds. It is one of the most peaceful and undervisited spots in the entire area, particularly at dawn when the light on the pagoda is extraordinary and the bay below is still and quiet.\n\nJungle Beach, tucked behind the eastern headland of Unawatuna bay, is another essential discovery for those willing to make the short effort required to reach it. This small, wild cove has no commercial development of any kind — no restaurants, no sun-lounger vendors, no tuk-tuks waiting at the path's end. It is simply a curve of sand, some large boulders to sit on, calm water, and forest coming down to the shore. The snorkelling here is often better than at the main beach, and the sense of having found something secret and unspoiled is one of those small travel pleasures that remain vivid in memory long afterward.\n\nThe Rumassala Hill, which forms the eastern boundary of Unawatuna bay, is cloaked in dense jungle that according to local tradition has medicinal properties connected to the ancient epic Ramayana. A herbal garden and several Buddhist shrines are located within the forested hillside, and the area has been designated a protected zone. Walking trails through Rumassala offer a glimpse of the birdlife and vegetation of Sri Lanka's southern lowland forest within minutes of the beach — a reminder that beyond the restaurants and the sand, this is a place of considerable natural richness."
      },
      {
        title: language === 'EN' ? "Section 12: Final Thoughts — What Makes Unawatuna Stay With You" : "12 වන කොටස: අවසාන අදහස් — උණවටුන ඔබ සමඟ රැඳී සිටින්නේ ඇයි",
        body: "There are beaches in Sri Lanka that are more dramatic than Unawatuna, and there are places on the southern coast that are quieter or more pristine. But Unawatuna has something that is genuinely difficult to manufacture or replicate — a sense of place that feels both comfortable and alive, where the beauty of the bay and the warmth of the people who live and work around it combine into something that is more than the sum of its parts.\n\nIt is the kind of place where you arrive planning to stay two nights and find yourself extending to five. Where the rhythm of the day — a slow breakfast, a morning in the water, an afternoon reading in the shade, the first cold drink of the evening as the light turns gold on the western headland — becomes something you are reluctant to give up. Where the view from the sand as the sun drops behind the palms and the fishing boats head back toward Galle seems, briefly, like exactly enough.\n\nSri Lanka is full of extraordinary places, and the southern coast is one of its great gifts to travellers. Unawatuna sits at the heart of that coast — close to history, close to nature, close to the sea — and it has been drawing people back for decades for reasons that are entirely easy to understand once you have sat on that crescent of sand and looked out at the blue of the Indian Ocean spreading to the horizon."
      }
    ]
  };

  return (
    <div className="space-y-20">
      <header className="mb-20 border-b border-[#5A5A40]/10 pb-12">
        <span className="text-[11px] uppercase tracking-[0.5em] text-[#5A5A40]/60 font-medium">Coastal Destination</span>
        <h1 className="text-5xl md:text-7xl font-light tracking-tighter mt-6 mb-6 text-[#2d2d2d]">{content.title}</h1>
        <h2 className="text-2xl font-light text-[#2d2d2d]/70">{content.subtitle}</h2>
        <p className="text-sm text-[#2d2d2d]/50 mt-4 max-w-xl">{content.description}</p>
      </header>
      
      <div className="space-y-20">
        {content.sections.map((section, index) => (
          <section key={index} className="grid md:grid-cols-[200px,1fr] gap-8">
            <h3 className="text-[11px] uppercase tracking-[0.3em] text-[#5A5A40]/50 pt-2">{section.title.split(':')[0]}</h3>
            <div className="space-y-4">
              <h4 className="text-2xl md:text-3xl font-semibold text-black">{section.title.split(':')[1]}</h4>
              <p className="text-[#2d2d2d]/80 leading-relaxed font-light whitespace-pre-line">{section.body}</p>
            </div>
          </section>
        ))}
      </div>
    </div>
  );
};

export default AboutUnawatuna;
