import React from 'react';
import { Language } from '../types';

interface AboutLaxapanaFallsProps {
  language: Language;
}

const AboutLaxapanaFalls: React.FC<AboutLaxapanaFallsProps> = ({ language }) => {
  const content = {
    title: language === 'EN' ? "Complete Travel Guide — Laxapana Falls" : "සම්පූර්ණ සංචාරක මාර්ගෝපදේශය — ලක්ෂපාන ඇල්ල",
    subtitle: language === 'EN' ? "Sri Lanka's Tallest Waterfall — 126 Metres of Highland Water Falling into the Forest Below Adam's Peak" : "ශ්‍රී ලංකාවේ උසම දිය ඇල්ල - ශ්‍රී පාද කන්දට පහළින් පිහිටි මීටර් 126ක උසකින් යුත් දිය ඇල්ලකි",
    description: language === 'EN' ? "Nuwara Eliya District, Central Province • 126 m height • Natural waterfall site • Open year-round • Near Maskeliya, Hatton area" : "නුවරඑළිය දිස්ත්‍රික්කය, මධ්‍යම පළාත • උස මීටර් 126 • ස්වාභාවික දිය ඇල්ල • වසර පුරා විවෘතයි • හැටන් මාස්කෙළිය ප්‍රදේශය අසල",
    sections: [
      {
        title: language === 'EN' ? "Section 01: Introduction — Why Laxapana Falls Matters" : "01 වන කොටස: හැඳින්වීම — ලක්ෂපාන ඇල්ල වැදගත් වන්නේ ඇයි?",
        body: language === 'EN' ? 
          "Laxapana Falls is the tallest waterfall in Sri Lanka — a single, unbroken plunge of approximately 126 metres formed by the Maskeliya Oya as it drops over the edge of the highland escarpment in the Nuwara Eliya District, in the shadow of the Adam's Peak massif and within the broader highland catchment that feeds some of the island's most important rivers. At 126 metres, Laxapana is not only the tallest waterfall in Sri Lanka but one of the tallest single-drop waterfalls in South Asia, and the physical fact of that height produces at the viewpoint a response to vertical scale that is genuinely different from the experience of any of the shorter highland waterfalls of the central province.\n\nLaxapana is situated in a part of the central highlands that is less well-known to the international tourist circuit than the Nuwara Eliya plateau or the Ella corridor — the area around Maskeliya, Norton Bridge, and the Laxapana hydroelectric complex is working highland country, centred on tea estates and the infrastructure of the Laxapana Power Station rather than on tourism accommodation. This relative obscurity gives the Laxapana visit a quality of discovery and unprogrammed encounter that the more established waterfall destinations of the highland circuit cannot consistently provide. Finding Laxapana requires a degree of effort and local knowledge that is itself part of the experience, and what you find at the end of the approach is the falls themselves, in their full scale.\n\nThe context of Laxapana is as significant as the falls themselves. The Maskeliya Oya that forms the falls drains a watershed that includes the southern slopes of the Adam's Peak massif — Sri Lanka's most sacred mountain — and the reservoir systems that feed the Laxapana hydroelectric complex, one of the island's most important power generation facilities. The falls exist at the intersection of this sacred natural geography and this practical engineering infrastructure, enriching the experience with a complexity of context that simple scenic tourism rarely offers." :
          "ලක්ෂපාන ඇල්ල ශ්‍රී ලංකාවේ උසම දිය ඇල්ලයි - එය නොකඩවා මීටර් 126ක් පමණ පහළට ඇද හැලෙන තනි ජල ධාරාවකි. මාස්කෙළිය ඔය මඟින් නිර්මාණය වන මෙම දිය ඇල්ල, නුවරඑළිය දිස්ත්‍රික්කයේ ශ්‍රී පාද කඳුවැටියට පහළින් පිහිටා ඇත. මීටර් 126ක උසකින් යුත් ලක්ෂපාන, ලංකාවේ උසම දිය ඇල්ල පමණක් නොව දකුණු ආසියාවේ උසම තනි ජල ධාරාවකින් යුත් දිය ඇලි අතරින් එකක් ද වේ.\n\nනුවරඑළිය හෝ ඇල්ල වැනි ජාත්‍යන්තර සංචාරකයන් අතර ජනප්‍රිය ප්‍රදේශවලට වඩා ලක්ෂපාන ඇල්ල පිහිටා ඇත්තේ සංචාරක කර්මාන්තයට වඩා තේ වගාව සහ ජල විදුලි නිෂ්පාදනය මූලික කරගත් හැටන් නෝටන් බ්‍රිජ් මාස්කෙළිය ප්‍රදේශයේය. මේ නිසා වෙනත් ජනප්‍රිය දිය ඇලිවලට වඩා මෙය නැරඹිය යුතු විශේෂ, නිදහස් පරිසරයක් සහිත ස්ථානයක් බවට පත්ව ඇත.\n\nශ්‍රී ලංකාවේ පූජනීයම කන්ද වන ශ්‍රී පාදයේ දකුණු බෑවුම්වලින් ගලා එන ජලයෙන් මාස්කෙළිය ඔය පෝෂණය වේ. එසේම ශ්‍රී ලංකාවේ ප්‍රධානතම ජල විදුලි ව්‍යාපෘතියක් වන ලක්ෂපාන ජල විදුලි බලාගාරය සඳහා ද මෙම ජලය යොදා ගැනේ. එබැවින් මෙම දිය ඇල්ල පූජනීය භූගෝලීය පසුබිමක් මෙන්ම වැදගත් ඉංජිනේරුමය වටිනාකමක් ද දරයි."
      },
      {
        title: language === 'EN' ? "Section 02: History — The Maskeliya Oya and the Power of Highland Water" : "02 වන කොටස: ඉතිහාසය — මාස්කෙළිය ඔය සහ මධ්‍යම කඳුකරයේ ජලයේ බලය",
        body: language === 'EN' ?
          "The Maskeliya Oya has one of the most consequential histories of any highland stream in Sri Lanka, not primarily because of the waterfall it creates but because of the hydroelectric power that the combined highland rivers of the Adam's Peak catchment generate. The Laxapana Power Station, commissioned in 1950 as Sri Lanka's first major hydroelectric facility, was a landmark achievement of the early post-independence period. The falls were already a known and celebrated natural feature, and the decision to name the power station after the waterfall reflects the primacy of the natural feature in the local understanding.\n\nThe broader water management system — which includes the Castlereagh Reservoir, the Moussakelle Reservoir, and a network of tunnels, channels, and penstocks — represents one of the most ambitious exercises in highland hydraulic engineering in Sri Lanka's modern history. The relationship between the hydroelectric infrastructure and the natural waterfall is complex: the flow of the Maskeliya Oya through the falls is affected by the operational decisions of the power system's management in ways that are not always predictable from natural rainfall patterns alone.\n\nThe name Laxapana itself is believed to derive from a Sinhala phrase meaning the place where a hundred thousand lamps are lit — a reference to the tradition of lighting lamps on the summit of Adam's Peak during the pilgrimage season, whose light, seen from the surrounding countryside on a clear night, would have produced exactly the impression of a vast illumination. The water that creates the falls descends from a catchment that pilgrims have been climbing toward for as long as the mountain has been considered sacred.\n\n\"Laxapana is where the water of Adam's Peak completes its work — gathering the rain of the highest sacred mountain and releasing it, in a single act of 126 metres, into the world below.\"" :
          "මාස්කෙළිය ඔයට ලංකාවේ වෙනත් කිසිදු කඳුකර ගංගාවකට නැති තරම් වැදගත් ඉතිහාසයක් ඇත. එයට හේතුව දිය ඇල්ලම පමණක් නොව ශ්‍රී පාද රක්ෂිතයෙන් එකතු වන ජලයෙන් නිපදවන ජල විදුලියයි. 1950 වසරේදී ශ්‍රී ලංකාවේ ප්‍රථම ප්‍රධාන ජල විදුලි බලාගාරය ලෙස ලක්ෂපාන බලාගාරය ආරම්භ කිරීම නිදහසින් පසු යුගයේ සුවිශේෂී සන්ධිස්ථානයක් විය.\n\nකාසල්රී ජලාශය, මවුස්සාකැලේ ජලාශය සහ උමං මාර්ග ජාලයකින් සමන්විත මෙම පුළුල් ජල කළමනාකරණ පද්ධතිය ශ්‍රී ලංකාවේ නවීන ඉතිහාසයේ දැවැන්තම වාරිමාර්ග ඉංජිනේරු ව්‍යාපෘතියක් ලෙස සැලකේ. විදුලිබල මණ්ඩලයේ විදුලි ජනන තීරණ මත දිය ඇල්ලේ ජල ප්‍රවාහය අඩු වැඩි වන බැවින් ස්වභාවික වර්ෂාපතනයට අමතරව එහි බලපෑම ද දිය ඇල්ලට ඇත.\n\nලක්ෂපාන යන නම සෑදී ඇත්තේ 'ලක්ෂයක් පහන් දැල්වෙන ස්ථානය' යන අරුතෙනි. ශ්‍රී පාද වන්දනා සමයේදී කඳු මුදුනේ දල්වන පහන්වල ආලෝකය ඈතට දිස්වෙන ආකාරය සිහිපත් කරමින් මෙම ප්‍රදේශයට එම නම ලැබී ඇති බව විශ්වාස කෙරේ. කන්ද පූජනීයත්වයට පත් වූ දා සිටම, වන්දනාකරුවන් ගමන් කරන භූමියෙන් ගලා එන ජලයෙන් මෙම දිය ඇල්ල සැකසී ඇත.\n\n\"ලක්ෂපාන යනු ශ්‍රී පාදයේ ජලය සිය කාර්යය සම්පූර්ණ කරන ස්ථානයයි - පූජනීය කන්දේ වර්ෂාව එකතු කර, එය මීටර් 126ක තනි නැම්මකින් පහළ ලෝකයට මුදාහරියි.\""
      },
      {
        title: language === 'EN' ? "Section 03: The Falls — Scale, Power, and the Experience of 126 Metres" : "03 වන කොටස: දිය ඇල්ල — ප්‍රමාණය, බලය සහ මීටර් 126ක අත්දැකීම",
        body: language === 'EN' ?
          "The experience of encountering Laxapana Falls for the first time — confronting the full 126-metre height of the descending water — is one of the most viscerally impressive natural encounters available in the Sri Lankan central highlands. The response it produces is more intense, more physically immediate, and more difficult to translate than knowing its measurements.\n\nThe Maskeliya Oya at the falls lip is a substantial highland river drawing from a large catchment, and the volume of water passing over the escarpment edge at Laxapana in full flow is considerable. This produces a plunge pool of considerable depth and a spray cloud of corresponding density that makes the immediate vicinity of the viewpoint one of the most physically immersive waterfall environments on the island. The sound at the viewpoint — the sustained, deep, resonant roar of 126 metres of falling water amplified by the gorge walls — is felt in the body as much as heard by the ears.\n\nThe rock face over which Laxapana descends is a sheer highland escarpment of dark, metamorphic rock, permanently wet and heavily colonised by mosses, algae, and ferns. In good light — particularly the early morning light that enters the gorge — the interaction between the white water, the dark rock, and the green of the moss produces a colour contrast of exceptional visual intensity." :
          "පළමු වරට ලක්ෂපාන ඇල්ලේ මීටර් 126ක දැවැන්ත ජල ධාරාව දැකීම, ශ්‍රී ලංකාවේ මධ්‍යම කඳුකරයේදී ලබාගත හැකි විශ්මිතම ස්වාභාවික අත්දැකීමකි. එහි උස සහ ප්‍රමාණය මනසට ග්‍රහණය කරගැනීම, සාමාන්‍ය කුඩා දිය ඇල්ලක් නැරඹීමට වඩා බෙහෙවින් වෙනස් දැඩි හැඟීමක් ජනිත කරයි.\n\nමාස්කෙළිය ඔය යනු විශාල පෝෂක ප්‍රදේශයකින් ජලය ලබාගන්නා ප්‍රධාන ගංගාවක් වන අතර, ජලය පිරුණු කාලයට ලක්ෂපානින් පහළට වැටෙන ජල කඳ අතිවිශාලය. ඒ හේතුවෙන් දිය ඇල්ල පාමුල ඉතා ගැඹුරු තටාකයක් සහ ඝන මීදුමක් නිර්මාණය වන අතර, එමඟින් නරඹන්නාට සැබැවින්ම දිය ඇල්ල හා එක්වූවාක් වැනි හැඟීමක් ගෙනදෙයි. දිය ඇල්ලේ හඬ නිකම්ම ඇසෙනවාට වඩා, එය ශරීරයටම දැනෙන ප්‍රබල නාදයක් බවට පත්වේ.\n\nඅඳුරු පැහැති ආග්නේය පාෂාණ මතින් කඩා හැලෙන මෙම ජල ධාරාව අවට, නිරන්තරයෙන්ම තෙත් වූ පරිසරයක් පවතින බැවින් පාසි, ඇල්ගී සහ මීවන ගස්වලින් පිරී පවතී. විශේෂයෙන් උදෑසන හිරු එළිය වැටෙන විට, සුදු පැහැති ජලයත්, අඳුරු ගල් තලාවත්, කොළ පැහැති පරිසරයත් එකිනෙක ගැටීමෙන් නිර්මාණය වන්නේ අතිශය සුන්දර දර්ශනයකි."
      },
      {
        title: language === 'EN' ? "Section 04: Getting to the Viewpoint — The Approach and the Access" : "04 වන කොටස: නැරඹුම් ස්ථානයට ළඟාවීම — ප්‍රවේශය සහ ගමන් මාර්ගය",
        body: language === 'EN' ?
          "Reaching the Laxapana Falls viewpoint is the aspect of the visit that distinguishes it from more formal waterfall sites. The approach involves a drive through the Maskeliya area and then a walk through the surrounding landscape. The terrain around the falls is steep and in some sections genuinely rugged, and the approach requires appropriate footwear and a reasonable level of physical fitness.\n\nThe most commonly used approach to the Laxapana Falls viewpoint begins near the village of Laxapana. From the road, a path descends through tea estate margins, scrub forest, and the established forest of the upper gorge. This descent involves a demanding gradient that is considerably more demanding on the return climb. The total time required ranges from one to two hours depending on pace.\n\nA local guide is strongly recommended for the Laxapana approach. Engaging one of these guides — through enquiry at local tea estate offices or accommodation — transforms the visit from an uncertain navigation exercise into a confident encounter with the falls." :
          "ලක්ෂපාන ඇල්ලට ළඟාවීම අනෙකුත් පහසුවෙන් නැරඹිය හැකි දිය ඇලිවලින් එය වෙනස් කරන ප්‍රධාන සාධකයකි. මාස්කෙළිය හරහා වාහනයකින් ගොස්, පසුව අවට පරිසරය හරහා පාගමනකින් යායුතු වේ. ඇතැම් ස්ථානවල බෑවුම් සහිත දුෂ්කර මාර්ග පවතින බැවින්, සුදුසු සපත්තු පැළඳීම සහ හොඳ ශාරීරික යෝග්‍යතාවක් තිබීම වැදගත්ය.\n\nලක්ෂපාන ගම්මානය අසලින් ආරම්භ වන ප්‍රධාන ප්‍රවේශ මාර්ගය, තේ වතු, ලඳු කැලෑ සහ ඝන වනාන්තරය හරහා පහළට ගමන් කරයි. පහළට බසිද්දී වඩා ආපසු ඉහළට නැගීමේදී මෙම ගමන බෙහෙවින් අපහසු වේ. සාමාන්‍ය වේගයකින් ගමන් කරන්නේ නම් ගොස් ඒමට පැය එකත් දෙකත් අතර කාලයක් ගතවේ.\n\nමෙම ගමන සඳහා ප්‍රාදේශීය මගපෙන්වන්නෙකුගේ සහාය ලබාගැනීම බෙහෙවින් නිර්දේශ කෙරේ. තේ වතු ආශ්‍රිතව හෝ ඔබ නවාතැන් ගන්නා ස්ථානයෙන් මෙවැනි මගපෙන්වන්නෙකු සොයාගැනීමෙන් ඔබගේ ගමන වඩාත් ආරක්ෂිත සහ පහසු එකක් වනු ඇත."
      },
      {
        title: language === 'EN' ? "Section 05: The Surrounding Landscape — Tea, Forest, and the Adam's Peak Massif" : "05 වන කොටස: අවට පරිසරය - තේ, වනාන්තරය සහ ශ්‍රී පාද කඳුවැටිය",
        body: language === 'EN' ?
          "The landscape surrounding Laxapana Falls sits at the point where the cultivated highland plateau — covered almost entirely in tea estates — meets the wild, forested escarpment. This boundary between human agricultural transformation and natural forest is one of the most vivid demonstrations of the stark line drawn by colonial plantation development.\n\nThe Adam's Peak massif is visible from various points on clear days. The falls are literally downstream of one of the most venerated mountains in the world, and the awareness of it gives the encounter a dimension of meaning that transcends the purely geological.\n\nThe forest of the Laxapana gorge is one of the finest surviving examples of intermediate wet zone forest in the central highlands, combining elements of lowland rainforest and montane cloud forest. The bird community is exceptional, with several endemic species encountered by visitors who walk the approach path with appropriate attention." :
          "ලක්ෂපාන ඇල්ල අවට පරිසරය තේ වතුවලින් වැසීගිය වගා බිම්වල සහ වනගත කඳු බෑවුම්වල හමුවන සීමාවේ පිහිටා ඇත. මෙම කෘෂිකාර්මික වගා බිම් සහ ස්වාභාවික වනාන්තරය අතර ඇති මායිම, යටත් විජිත සමයේ වතු වගාවේ ව්‍යාප්තිය මනාව පිළිඹිබු කරයි.\n\nපැහැදිලි දිනයකදී ශ්‍රී පාද කඳුවැටිය මෙහි බොහෝ ස්ථානවලට දර්ශනය වේ. ලෝකයේ පූජනීයම කන්දකින් ගලා එන ජලයෙන් නිර්මාණය වන දිය ඇල්ලක් වීම නිසාම, එයට අද්විතීය ආධ්‍යාත්මික වටිනාකමක් ද එක්වී ඇත.\n\nලක්ෂපාන නිම්නයේ පවතින වනාන්තරය, මධ්‍යම කඳුකරයේ තෙත් කලාපීය සහ කඳුකර වනාන්තර ලක්ෂණ දෙකම මුසු වූ සුවිශේෂී පරිසර පද්ධතියකි. මෙහි ශ්‍රී ලංකාවට ආවේණික පක්ෂි විශේෂ රැසක් දැකගත හැකි අතර, පරිසරයට ආදරය කරන්නෙකුට මෙය අපූරු අත්දැකීමක් ගෙනදෙයි."
      },
      {
        title: language === 'EN' ? "Section 06: The Hydroelectric Complex — Water, Power, and the Engineering" : "06 වන කොටස: ජල විදුලි ව්‍යාපෘතිය - ජලය, බලය සහ ඉංජිනේරු ශිල්පය",
        body: language === 'EN' ?
          "The Laxapana hydroelectric complex encompasses multiple reservoir systems, tunnels bored through the highland rock, penstocks descending the escarpment, and a series of generation stations. Its cumulative engineering achievement is genuinely impressive.\n\nThe Laxapana Power Station itself — the original generation facility commissioned in 1950 — is visible from various points in the approach to the falls and provides an industrial counterpoint to the natural spectacle. The engineers who sited the power station were responding to the same vertical energy that the Maskeliya Oya expresses in falling 126 metres at Laxapana Falls.\n\nThe Castlereagh Reservoir, located upstream of the falls, provides a landscape feature of considerable scenic quality in its own right. The combination of the reservoir visit with the Laxapana Falls approach creates a complete engagement with the highland water landscape." :
          "ලක්ෂපාන ජල විදුලි සංකීර්ණය ජලාශ, උමං මාර්ග සහ විදුලි බලාගාර කිහිපයකින් සමන්විත විශාල ඉංජිනේරු ව්‍යාපෘතියකි. මෙහි සමස්ත ක්‍රියාකාරිත්වය සහ ජයග්‍රහණ සැබැවින්ම විශ්මයජනකය.\n\n1950 දී ආරම්භ කරන ලද මුල්ම ලක්ෂපාන විදුලි බලාගාරය දිය ඇල්ල වෙත යන ගමන් මාර්ගයේදී දැකගත හැකිය. මාස්කෙළිය ඔයේ මීටර් 126ක උසකින් කඩා හැලෙන ජලයේ ගැබ්වී ඇති අතිමහත් බලය යොදාගැනීම ඉංජිනේරුවන්ගේ ප්‍රධාන අරමුණ විය.\n\nදිය ඇල්ලට ඉහළින් පිහිටි කාසල්රී ජලාශය, අවට පරිසරයට එක් කරන්නේ අපූරු සුන්දරත්වයකි. කාසල්රී ජලාශය සහ ලක්ෂපාන ඇල්ල එකවර නැරඹීමෙන් මධ්‍යම කඳුකරයේ ජල සම්පත යොදාගන්නා අයුරු මනාව අවබෝධ කරගත හැකිය."
      },
      {
        title: language === 'EN' ? "Section 07: Photography — The Challenge of 126 Metres" : "07 වන කොටස: ඡායාරූපකරණය - මීටර් 126ක අභියෝගය",
        body: language === 'EN' ?
          "Photographing Laxapana Falls presents challenges of scale. Fitting the full 126-metre height into a single frame from a viewpoint close enough to be within the spray zone is a challenge no lens can fully resolve. The photographer must choose between a wide-angle view that captures the full height but renders details small, and a longer focal length that shows specific sections.\n\nThe most experienced photographers assemble a portfolio of the falls conveying both overall scale and specific detail. Deep wide-angle shots, close-ups of the lip, mid-fall segments, and spray zone images collectively record the Laxapana experience.\n\nThe gorge setting limits direct sunlight. Early morning light provides the most favourable illumination. Dense spray requires constant management of lens moisture with a microfibre cloth and a camera rain cover. Long exposure techniques produce visually compelling static forms but require a sturdy tripod capable of withstanding ground vibrations." :
          "ලක්ෂපාන ඇල්ල ඡායාරූපකරණය කිරීම එහි අතිමහත් ප්‍රමාණය නිසාම විශාල අභියෝගයකි. මීදුම සහ ජල බිඳිති සහිත කලාපයේ සිට මීටර් 126ම එකම රාමුවකට හසුකරගැනීම කිසිදු කාචයකට පහසු කටයුත්තක් නොවේ. සම්පූර්ණ උස පෙන්වන පුළුල් කෝණ (Wide-angle) ඡායාරූප සහ කුඩා කොටස් පෙන්වන සමීප රූප අතරින් තේරීමක් කිරීමට ඡායාරූප ශිල්පියාට සිදුවේ.\n\nදක්ෂ ඡායාරූප ශිල්පීන් කරන්නේ සම්පූර්ණ දිය ඇල්ලම එක් ඡායාරූපයකින් පෙන්වනවා වෙනුවට, විවිධ කෝණවලින් ගත් ඡායාරූප කිහිපයක් එකතු කර එහි සැබෑ ස්වභාවය විදහාපෑමයි.\n\nඋදෑසන කාලයේ ලැබෙන ආලෝකය ඡායාරූප සඳහා වඩාත් සුදුසුය. ඝන මීදුම සහ ජල බිඳිති නිසා නිරන්තරයෙන්ම කැමරා කාචය පිසදැමීමට සහ එය ජලයෙන් ආරක්ෂා කරගැනීමට පියවර ගත යුතුය. ජලය ගලායන ස්වභාවය පෙන්වන Long exposure ඡායාරූප සඳහා කම්පනවලට ඔරොත්තු දෙන ත්‍රයිපෝඩයක් (Tripod) අනිවාර්ය වේ."
      },
      {
        title: language === 'EN' ? "Section 08: Practical Details and Logistics" : "08 වන කොටස: ප්‍රායෝගික තොරතුරු - ඔබ දැනගත යුතු දෑ",
        body: language === 'EN' ?
          "Height of falls: ~126 metres | Ranking: Tallest in Sri Lanka | Nearest town: Maskeliya / Hatton | Walk to viewpoint: 30–60 min each way\n\nThere is no formal entry ticket system, though small charges may be requested by local guides. There are no reliable restaurants or refreshment vendors at the site; bring water and snacks. The approach path can be challenging after recent rainfall.\n\nEngage a local guide for safety and navigation. Carry significantly more water than you think you will need for the demanding return climb. Do not attempt to approach the base of the falls closer than the established viewpoint permits; the plunge pool is dangerous with severe turbulence." :
          "උස: මීටර් 126 පමණ | ස්ථානය: ශ්‍රී ලංකාවේ උසම දිය ඇල්ල | ආසන්නතම නගරය: මාස්කෙළිය / හැටන් | නැරඹුම් මධ්‍යස්ථානයට ගමන: විනාඩි 30-60 පමණ\n\nවිධිමත් ප්‍රවේශපත්‍ර ක්‍රමයක් නොමැති වුවත් ප්‍රාදේශීය මගපෙන්වන්නන් සුළු මුදලක් අය කළ හැකිය. අවට අවන්හල් හෝ කඩ සාප්පු නොමැති බැවින් ජලය සහ ආහාර රැගෙන යාම අනිවාර්ය වේ. වර්ෂාවෙන් පසු ගමන් මාර්ගය ලිස්සන සුළු විය හැකිය.\n\nඔබගේ ආරක්ෂාව සඳහා ප්‍රාදේශීය මගපෙන්වන්නෙකුගේ සහාය ලබාගන්න. නැවත ඉහළට පැමිණීමේදී වැයවන ශක්තිය වෙනුවෙන් ප්‍රමාණවත් තරම් ජලය රැගෙන යන්න. දිය ඇල්ල පාමුලට ළඟාවීමෙන් වළකින්න; එහි ඇති ජල ප්‍රවාහය සහ ගැඹුරු තටාකය ඉතා අනතුරුදායකය."
      },
      {
        title: language === 'EN' ? "Section 09: Best Time to Visit" : "09 වන කොටස: සංචාරයට සුදුසුම කාලය",
        body: language === 'EN' ?
          "The visual impact of Laxapana is highly flow-dependent. At maximum flow — from October through January after the northeast monsoon — Laxapana is one of the most impressive natural spectacles in Sri Lanka. At low flow (March to May), the falls narrow but continue to display vertical drama.\n\nThe hydroelectric regulation of the Maskeliya Oya adds an additional variable. Reservoir management can affect the volume of water passing over the falls in unpredictable ways, meaning enquiring locally about current conditions is worthwhile before traveling for peak-flow photography.\n\nThe early morning visiting window applies here as with all highland falls. On a clear morning, the combination of light on the white water, the roaring sound filling the gorge, and the mist rising into the still air creates a natural spectacle of the first order." :
          "ලක්ෂපාන ඇල්ලේ සුන්දරත්වය සම්පූර්ණයෙන්ම රඳා පවතින්නේ ජල ප්‍රමාණය මතය. ඔක්තෝබර් සහ ජනවාරි අතර ඊසානදිග මෝසම් කාලයෙන් පසු උපරිම ජල ප්‍රවාහයක් පවතින විට මෙය ලංකාවේ අතිශය චමත්කාරජනක දසුනක් මවයි. වියළි කාලවලදී (මාර්තු සිට මැයි) මෙහි ජල ප්‍රවාහය අඩුවූවත් ඉහළින් කඩාහැලෙන සොබාදහමේ අසිරිය එලෙසම පවතී.\n\nමාස්කෙළිය ඔයේ ජල කළමනාකරණය ද දිය ඇල්ලට බලපායි. ජලාශයේ ක්‍රියාකාරකම් මත දිය ඇල්ලේ ජල මට්ටම අනපේක්ෂිත ලෙස වෙනස් විය හැකිය. එබැවින් ඡායාරූපකරණයට යනවා නම් ඒ පිළිබඳව පූර්ව දැනුවත් වීමක් ලබාගැනීම වැදගත්ය.\n\nඅනෙකුත් කඳුකර දිය ඇලි මෙන්ම ලක්ෂපාන නැරඹීමට ද හොඳම කාලය උදෑසනය. පැහැදිලි උදෑසනක, සුදෝසුදු ජල කඳට වැටෙන හිරු කිරණ, කඳු අතරින් ඇසෙන ජලයේ ඝෝෂාව සහ ඉහළට නැගෙන මීදුම කිසිදා අමතක නොවන සුන්දර දර්ශනයක් මවයි."
      },
      {
        title: language === 'EN' ? "Section 10: Getting There — The Road to Laxapana" : "10 වන කොටස: ළඟා වන ආකාරය - ලක්ෂපාන වෙත යන ගමන",
        body: language === 'EN' ?
          "Laxapana Falls is reached from Hatton via the road through Maskeliya and Norton Bridge. From Hatton, it is about 18 km (35 minutes) by car or tuk-tuk on winding highland roads passing through tea estates.\n\nHatton is the practical base for a Laxapana visit, connected to the rest of the highlands by the A7 highway and the scenic railway linking it to Colombo and Badulla.\n\nThe Adam's Peak pilgrimage access point at Nallathanniya is approx 20 km from Hatton. Combining the night-time Adam's Peak climb and the morning Laxapana waterfall visit creates two entirely memorable highland experiences using the same Hatton base." :
          "නෝටන් බ්‍රිජ් සහ මාස්කෙළිය හරහා දිවෙන මාර්ගයෙන් හැටන් සිට ලක්ෂපාන ඇල්ලට ළඟා විය හැකිය. සම්පූර්ණ දුර ප්‍රමාණය කිලෝමීටර් 18ක් පමණ වන අතර වාහනයකින් ගමන් කිරීමට විනාඩි 35ක් පමණ ගතවේ.\n\nකොළඹ සිට සහ බදුල්ලේ සිට පැමිණෙන අය සඳහා A7 මාර්ගයත්, දුම්රිය මාර්ගයත් හරහා හැටන් නගරය කේන්ද්‍ර කරගනිමින් මේ ගමන සැලසුම් කිරීම වඩාත් පහසුය.\n\nශ්‍රී පාද වන්දනාව ආරම්භ කරන නල්ලතන්නිය ප්‍රදේශය ද හැටන් සිට කිලෝමීටර් 20ක් පමණ දුරින් පිහිටා ඇත. රාත්‍රියේ ශ්‍රී පාදස්ථානය කරුණා කර, පසුදින උදෑසන ලක්ෂපාන ඇල්ල නැරඹීම මධ්‍යම කඳුකරයේ ලබන අමතක නොවන අත්දැකීමක් වනු ඇත."
      }
    ]
  };

  return (
    <div className="space-y-20">
      <header className="mb-20 border-b border-[#5A5A40]/10 pb-12">
        <span className="text-[11px] uppercase tracking-[0.5em] text-[#5A5A40]/60 font-medium">Highland Waterfall</span>
        <h1 className="text-5xl md:text-7xl font-light tracking-tighter mt-6 mb-6 text-[#2d2d2d]">{content.title}</h1>
        <h2 className="text-2xl font-light text-[#2d2d2d]/70">{content.subtitle}</h2>
        <p className="text-sm text-[#2d2d2d]/50 mt-4 max-w-xl">{content.description}</p>
      </header>
      
      <div className="space-y-20">
        {content.sections.map((section, index) => (
          <section key={index} className="grid md:grid-cols-[200px,1fr] gap-8">
            <h3 className="text-[11px] uppercase tracking-[0.3em] text-[#5A5A40]/50 pt-2">{section.title.split('—')[0].trim()}</h3>
            <div className="space-y-4">
              <h4 className="text-2xl md:text-3xl font-semibold text-black">{section.title.split('—')[1]?.trim() || section.title.split(':')[1]?.trim() || ''}</h4>
              <p className="text-[#2d2d2d]/80 leading-relaxed font-light whitespace-pre-line">
                {section.body.split('\n\n').map((paragraph, pIndex) => (
                  <React.Fragment key={pIndex}>
                    <span className={paragraph.startsWith('"') || paragraph.startsWith('\"') ? 'text-xl md:text-2xl italic border-l-4 border-[#5A5A40] pl-6 my-10 font-medium block' : ''}>
                      {paragraph}
                    </span>
                    {pIndex < section.body.split('\n\n').length - 1 && <><br /><br /></>}
                  </React.Fragment>
                ))}
              </p>
            </div>
          </section>
        ))}
      </div>
    </div>
  );
};

export default AboutLaxapanaFalls;
