import React from 'react';
import { Language } from '../types';
import { getOptimizedImageUrl } from '../lib/utils';

interface AboutSigiriyaProps {
  language: Language;
}

const AboutSigiriya: React.FC<AboutSigiriyaProps> = ({ language }) => {
  const content = {
    title: language === 'EN' ? "Complete Travel Guide — Sigiriya" : "සම්පූර්ණ සංචාරක මාර්ගෝපදේශය — සීගිරිය",
    subtitle: language === 'EN' ? "Sri Lanka's Ancient Sky Fortress — The Eighth Wonder of the World" : "ශ්‍රී ලංකාවේ පැරණි අහස් බලකොටුව — ලෝකයේ අටවන පුදුමය",
    description: language === 'EN' ? "Dambulla, Central Province • UNESCO World Heritage Site • Open Daily • All year round" : "දඹුල්ල, මධ්‍යම පළාත • යුනෙස්කෝ ලෝක උරුම අඩවියක් • දිනපතා විවෘතයි • වසර පුරා",
    sections: [
      {
        title: language === 'EN' ? "Section 01: Introduction — Why Sigiriya Matters" : "01 වන කොටස: හැඳින්වීම — සීගිරිය වැදගත් වන්නේ ඇයි",
        body: "Sigiriya, known in Sinhala as \"Lion Rock,\" is without question one of the most extraordinary human achievements in all of South Asia. Rising nearly 200 metres straight out of the flat jungle plains of Sri Lanka's Cultural Triangle, this colossal volcanic rock column has commanded the landscape for over 1,600 years. Today it stands as Sri Lanka's most visited archaeological site and one of the best-preserved examples of ancient urban planning anywhere in the world.\n\nWhat makes Sigiriya so remarkable is not simply its sheer physical size, though that is breathtaking enough. It is the totality of what was built here — a fortified palace complex of extraordinary ambition and sophistication, complete with hydraulic systems, symmetrical pleasure gardens, reflective water pools, frescoes painted on sheer cliff faces, and a summit palace accessible only through a doorway framed by the paws of a gigantic lion. To stand at its base and look upward is to feel the weight of ancient ingenuity bearing down on you.\n\nDeclared a UNESCO World Heritage Site in 1982, Sigiriya is formally known as the Ancient City of Sigiriya. It is one of eight such designated heritage sites in Sri Lanka and is, by most accounts, the most visited of them all. For any traveller journeying through this island nation, a visit to Sigiriya is not optional — it is essential."
      },
      {
        title: language === 'EN' ? "Section 02: History — The Rise and Fall of a Royal Fortress" : "02 වන කොටස: ඉතිහාසය — රාජකීය බලකොටුවක නැගීම සහ වැටීම",
        body: "The story of Sigiriya begins with an act of betrayal. In the 5th century CE, a Sinhalese prince named Kashyapa murdered his father, King Dhatusena, and seized the throne of the ancient kingdom of Anuradhapura. Fearing the vengeance of his half-brother Moggallana — the rightful heir who had fled to India — Kashyapa chose to abandon the traditional royal capital and build himself an entirely new palace in a location that could be defended from attack.\n\nHe chose Sigiriya, a massive granite inselberg that had likely been used as a monastery site by Buddhist monks for centuries before him. Between approximately 477 CE and 495 CE, Kashyapa oversaw the transformation of this bare rock into one of the ancient world's most impressive royal complexes. He designed elaborate water gardens on the plains below, a series of terraced gardens climbing the slopes, and a summit palace protected by the famous lion gateway. The entire project reflected both supreme confidence and profound paranoia.\n\nHis reign lasted eighteen years. When Moggallana returned from India with an army, the battle that followed was decisive. Kashyapa's forces deserted him and, according to historical accounts, he took his own life rather than be captured. Moggallana reclaimed the throne, moved the capital back to Anuradhapura, and Sigiriya was once again handed over to Buddhist monks, who used it as a monastery for several more centuries before it was eventually abandoned and swallowed by the jungle. It would not be rediscovered and excavated properly until the 19th and 20th centuries.\n\n\"Kashyapa built his palace in the sky — Sigiriya was his declaration to the world that no force on earth could reach him.\""
      },
      {
        title: language === 'EN' ? "Section 03: The Layout — Understanding the Complex" : "03 වන කොටස: සැලැස්ම — සංකීර්ණය අවබෝධ කර ගැනීම",
        body: "Sigiriya is not simply a rock with a ruin on top. It is a carefully designed multi-layered complex that extends across a wide area of the surrounding plains. To appreciate what you are walking through, it helps to understand how the site is structured before you arrive, as each zone was engineered with deliberate purpose.\n\nThe outermost boundary of the complex is a large moat and rampart system that once enclosed the entire city. As you enter through the main western gate, you step immediately into the Water Gardens — one of the oldest surviving landscaped gardens in the world. These symmetrical gardens feature pools, fountains, and channels laid out in precise geometric patterns. Remarkably, the hydraulic system that fed these fountains still functions during the rainy season, spraying water without any modern assistance. This alone tells you something extraordinary about the engineering skill of the people who built this place.\n\nBeyond the water gardens, the path narrows and begins to climb through the Boulder Gardens, a rocky landscape scattered with enormous granite boulders that were shaped and used by the builders as natural architectural elements. Caves and rock shelters cut into these boulders were used both as monk dwellings and as pleasure retreats. Then comes the Terraced Gardens, a series of ascending platforms cut into the lower slopes of the rock, creating a stairway of flat terraces that lead you upward toward the base of the main rock face.\n\nFrom here the famous climb begins — a pathway of metal staircases bolted into the cliff face that carries you up to the Fresco Gallery, then across the Mirror Wall, through the Lion's Paw platform, and finally to the summit plateau where the palace once stood. The ascent is steep and can be challenging in heat, but it is entirely manageable for most able-bodied visitors."
      },
      {
        title: language === 'EN' ? "Section 04: The Sigiriya Frescoes — Ancient Art on a Vertical Canvas" : "04 වන කොටස: සීගිරි බිතුසිතුවම් — සිරස් කැන්වසයක් මත පැරණි කලාව",
        body: "Halfway up the climb, tucked into a sheltered pocket in the sheer western face of the rock, you will find one of the most astonishing artworks to survive from the ancient world. The Sigiriya frescoes are a series of paintings depicting heavenly maidens — known variously as apsaras or ladies of the royal court — rendered in vivid natural pigments directly onto the rock face. They date back to the 5th century CE, making them among the oldest surviving painted artworks in Sri Lanka.\n\nOriginally, it is believed that the fresco gallery extended across a much larger section of the rock face, possibly depicting as many as 500 figures. Today only 22 figures survive, protected by the natural overhang of the cliff above them. Even so, they are magnificently preserved. The colours — ochres, reds, yellows, and greens derived from minerals and plant pigments — retain a warmth and vibrancy that feels almost impossible given their age. The women are depicted from the waist up, adorned with elaborate jewellery and headdresses, some holding lotus flowers, some offering gifts.\n\nThe identity of the figures remains a subject of scholarly debate. Some historians believe they represent the king's celestial consorts or court ladies. Others argue they are depictions of the goddess Tara or other divine feminine figures. Whatever their precise meaning, the frescoes are a masterwork of ancient Sri Lankan painting and a defining image of the entire Sigiriya site. Photography is permitted but flash photography is strictly prohibited to protect the pigments."
      },
      {
        title: language === 'EN' ? "Section 05: The Mirror Wall — A Gallery of Ancient Graffiti" : "05 වන කොටස: කැටපත් පවුර — පැරණි කුරුටු ගී ගැලරියක්",
        body: "Just below and beside the fresco gallery runs the Mirror Wall — a section of the cliff face that was once plastered with a polished coating of white lime, so smooth and reflective that it reportedly gleamed like a mirror and was used by King Kashyapa to see his own reflection as he walked past. Today, it is covered not in his reflection but in something equally fascinating: ancient graffiti.\n\nVisitors to Sigiriya began writing on the Mirror Wall as far back as the 6th century CE, etching comments, poems, reflections, and verses onto its surface using metal styluses. These inscriptions, known collectively as the Sigiriya Graffiti, number in the hundreds and have been catalogued as a significant historical document. Many of them are poems composed in response to the frescoes — expressions of admiration, longing, and beauty written by the literate visitors who climbed this rock a thousand years before us.\n\nThe inscriptions are written in an early form of Sinhala script and have been invaluable to scholars of the island's linguistic history. It is strictly forbidden for modern visitors to touch or add to the wall, and wardens are present to enforce this. But to stand before it and read translations of what ancient visitors wrote here is a deeply moving experience — a direct line of communication across fifteen centuries."
      },
      {
        title: language === 'EN' ? "Section 06: The Lion's Paw Platform — Gateway to the Summit" : "06 වන කොටස: සිංහ පාද මළුව — මුදුනට පිවිසුම",
        body: "As you continue climbing above the Mirror Wall, you reach a wide flat platform carved into the rock at approximately the halfway point of the ascent. This is the Lion's Paw Platform, named after the two enormous granite lion paws that flank the base of the final staircase leading to the summit. These paws are the sole surviving remnant of what was once a colossal lion sculpture — quite possibly standing 14 metres tall — whose open mouth served as the entrance gate to the summit palace above.\n\nThe symbolism was deliberate and powerful. The lion is the symbol of the Sinhalese people and of royal authority. Walking into the summit palace through the mouth of a lion was a declaration of divine kingship — a statement that the person who dwelled here was not simply a man but something closer to a deity. The scale of the engineering required to carve and construct this figure from solid rock at such altitude is staggering to consider.\n\nToday the paws remain perfectly intact, their enormous claws still clearly visible, and the platform offers one of the most dramatic views of the surrounding landscape available anywhere on the climb. Most visitors pause here for some time, catching their breath and taking in the view across the flat plains that extend to the horizon in every direction. On a clear day you can see the outline of Pidurangala Rock to the north and the distant shimmer of reservoirs to the east."
      },
      {
        title: language === 'EN' ? "Section 07: The Summit Palace — A Kingdom Above the Clouds" : "07 වන කොටස: මුදුනේ මාලිගාව — වලාකුළු වලට ඉහළින් වූ රාජධානියක්",
        body: "The final ascent from the Lion's Paw Platform to the summit is made via a series of steep metal staircases that were installed to replace the original rock-cut steps. It is the most physically demanding portion of the climb, particularly in the heat of the midday sun, but the reward at the top is profound. The summit of Sigiriya covers approximately 1.6 hectares — a surprisingly large plateau — and was once entirely covered by a sophisticated palace complex.\n\nWhat remains today are the foundations of the principal buildings, including the king's throne, several cisterns cut directly into the rock to collect rainwater, the outlines of gardens and pools that once occupied the summit plateau, and the remains of audience halls and service buildings. The central pool — a shallow rectangular cistern carved from solid granite — still holds water during the rainy season. The throne, a simple but imposing block of rock that has been shaped and hollowed to serve as a seat, faces west toward the direction of the setting sun.\n\nBut the most overwhelming aspect of the summit is not what you can see of the ruins — it is the view. From here, the entirety of Sri Lanka's ancient Cultural Triangle lays before you. The flat plains of the north-central province stretch in every direction. The jungle canopy below conceals the water gardens you walked through at ground level. Distant mountains mark the boundary of the island's central highlands. On a clear day the experience is genuinely sublime — a reminder of why Kashyapa chose this precise spot to build the home from which he intended to rule the world."
      },
      {
        title: language === 'EN' ? "Section 08: Practical Information — What You Need to Know" : "08 වන කොටස: ප්‍රායෝගික තොරතුරු — ඔබ දැනගත යුතු දේ",
        body: "Opening hours: 7:00 AM – 5:30 PM\nEntrance fee (foreign): USD 30 per person\nEntrance fee (SAARC): USD 15 per person\nClimb time: 1.5 – 3 hours\nHeight of rock: ~200 metres\nNearest town: Dambulla (17 km)\n\nThe entrance ticket covers access to the entire complex including the summit. It is advisable to book tickets in advance during peak tourist season (December to April) as the site enforces a daily visitor cap and queues can be very long. Tickets can be purchased online through the Central Cultural Fund website or at the site entrance, though on-site purchases may face longer waits.\n\nThe climb involves over 1,200 steps in total, including the metal staircases. The path is exposed in sections and can be slippery after rain. Comfortable, closed-toe shoes with good grip are strongly recommended. Sandals and flip-flops are strongly discouraged and can make the metal staircases genuinely dangerous. There is no shade on the final ascent, so sun protection is essential.\n\nVisitor tips:\nArrive at opening time (7:00 AM) to avoid the worst of the heat and the crowds. By 10:00 AM the site is significantly busier.\n\nCarry at least 1.5 litres of water per person. There are no water sellers on the rock itself, only at the base.\n\nBeware of the resident population of hornets near the fresco gallery — do not wave arms or shout near the cliff face.\n\nGuides are available for hire at the entrance gate and add significant depth to the experience, particularly for understanding the hydraulic gardens."
      },
      {
        title: language === 'EN' ? "Section 09: Best Time to Visit — Season and Light" : "09 වන කොටස: සංචාරය කිරීමට හොඳම කාලය — කාලගුණය සහ ආලෝකය",
        body: "Sri Lanka's climate means that Sigiriya is accessible year-round, but the experience differs considerably depending on when you go. The dry season in the Cultural Triangle runs roughly from May to September, with the most stable and comfortable weather typically found between June and August. During these months the skies are clear, the heat is dry rather than humid, and the views from the summit are at their most expansive. This is also a popular period for European visitors, so the site can be busy.\n\nThe island's peak tourist season runs from December to March, when the weather in the south and central regions is also generally excellent. January and February in particular offer superb conditions at Sigiriya — warm, clear days and cooler early mornings that make the climb more pleasant. This is also a period of significant visitor numbers, and the site can feel crowded by mid-morning. An early arrival is especially important during these months.\n\nThe monsoon season in the north-central province runs from October to January. During this period rain is possible, particularly in the afternoons. A wet Sigiriya is not without its own beauty — mist rolls across the jungle, the water gardens come alive, and the fresco colours seem deeper in diffused light — but the metal staircases become significantly more slippery and the summit views may be obscured. If you visit during these months, plan your climb for early morning and be prepared to be flexible.\n\nFor photography, the golden hours of early morning and late afternoon produce the most dramatic light on the rock face. The western fresco gallery is best lit in the morning. The summit views are most spectacular just after sunrise, before haze builds across the plains. If you are willing to arrive at opening time, the combination of golden light, cooler temperatures, and thinner crowds makes the experience considerably more rewarding."
      },
      {
        title: language === 'EN' ? "Section 10: Getting There — Reaching Sigiriya" : "10 වන කොටස: ගමන් මාර්ගය — සීගිරියට ළඟා වීම",
        body: "Sigiriya is located in the Matale District of Sri Lanka's Central Province, approximately 160 kilometres northeast of Colombo and about 17 kilometres north of the town of Dambulla. The most comfortable way to reach the site from Colombo is by private car or taxi, a journey that takes approximately three hours depending on traffic. Several reputable tour operators in Colombo and Kandy offer day trips and multi-day Cultural Triangle itineraries that include Sigiriya as a centrepiece.\n\nFor independent travellers, the public bus network connects Colombo and Kandy to Dambulla, from where local buses or three-wheeled tuk-tuks can carry you the final distance to Sigiriya village. The journey by public bus is slow but inexpensive and gives you the chance to see the countryside at a more intimate pace. From Kandy, the journey to Sigiriya takes approximately two to three hours by road and is one of the most popular day-trip routes on the island.\n\nThe nearest airport is Bandaranaike International Airport in Colombo. There is no direct train service to Sigiriya itself, though the train network connects Colombo to several towns in the region from which onward transport is straightforward. If you are planning to explore the broader Cultural Triangle — which also encompasses Anuradhapura, Polonnaruwa, and Dambulla — it is well worth hiring a car and driver for several days rather than attempting to piece together individual journeys on public transport. Accommodation is readily available in Sigiriya village itself, as well as in Dambulla, Habarana, and the surrounding area."
      },
      {
        title: language === 'EN' ? "Section 11: Nearby Attractions — Making the Most of the Region" : "11 වන කොටස: අවට ආකර්ෂණීය ස්ථාන — කලාපයෙන් උපරිම ප්‍රයෝජන ගැනීම",
        body: "A visit to Sigiriya pairs naturally with several other remarkable sites in the surrounding region. The most obvious companion is Pidurangala Rock, located approximately 1.5 kilometres north of Sigiriya. Pidurangala offers a scrambling climb that is harder and wilder than the maintained staircase route up Sigiriya, and rewards those who make it to the top with what many photographers consider the finest view of Sigiriya's rock in its entirety — particularly at sunrise. The climb to Pidurangala's summit involves scrambling over large boulders and requires a reasonable level of physical fitness, but the entrance fee is significantly lower than Sigiriya and the atmosphere is far less crowded.\n\nDambulla Cave Temple, a UNESCO World Heritage Site in its own right, is located just 17 kilometres to the south. This complex of five cave temples contains 153 Buddha statues and an extraordinary collection of ancient cave paintings covering walls and ceilings in vivid colour. The site dates back to the 1st century BCE and is still an active place of worship. The combination of Dambulla in the morning and Sigiriya in the afternoon — or vice versa — makes for an intensely rewarding single day in the Cultural Triangle.\n\nFurther afield, the ancient cities of Anuradhapura and Polonnaruwa are both within comfortable driving distance and together represent thousands of years of Sri Lanka's royal heritage. The Minneriya National Park, famous for its annual elephant gathering — one of the largest such congregations of wild Asian elephants anywhere on earth — is located approximately 25 kilometres from Sigiriya and can be visited as an afternoon safari following a morning climb of the rock. This combination of ancient monument and wildlife encounter in a single day is one of the most distinctive itinerary options available anywhere in Asia."
      },
      {
        title: language === 'EN' ? "Section 12: Final Thoughts — Why This Place Is Unforgettable" : "12 වන කොටස: අවසාන අදහස් — මෙම ස්ථානය අමතක නොවන එකක් වන්නේ ඇයි",
        body: "There are sites in the world that impress you with their scale, and there are sites that move you with their beauty, and then there are very rare places that do something more complex — that make you feel the weight of human ambition, creativity, and the unstoppable passage of time all at once. Sigiriya is one of those places.\n\nTo walk through the water gardens in the early morning light, to climb the ancient stone steps as the plains below you fall away, to stand before frescoes painted by hands fifteen centuries dead, to look out from the summit of a sky fortress built by a king who was certain he could outrun his own fate — it is an experience that stays with you long after you have descended and driven away into the surrounding jungle. Sigiriya is not simply an archaeological site. It is a story carved in stone, and one of the most extraordinary stories this island has to tell."
      }
    ]
  };

  return (
    <div className="space-y-20">
      <header className="mb-20 border-b border-[#5A5A40]/10 pb-12">
        <span className="text-[11px] uppercase tracking-[0.5em] text-[#5A5A40]/60 font-medium">Cultural Heritage</span>
        <h1 className="text-5xl md:text-7xl font-light tracking-tighter mt-6 mb-6 text-[#2d2d2d]">{content.title}</h1>
        <h2 className="text-2xl font-light text-[#2d2d2d]/70">{content.subtitle}</h2>
        <p className="text-sm text-[#2d2d2d]/50 mt-4 max-w-xl">{content.description}</p>
      </header>
      
      <div className="space-y-20">
        {content.sections.map((section, index) => (
          <section key={index} className="grid md:grid-cols-[200px,1fr] gap-8">
            <h3 className="text-[11px] uppercase tracking-[0.3em] text-[#5A5A40]/50 pt-2">{section.title.split(':')[0]}</h3>
            <div className="space-y-4">
              <h4 className="text-2xl md:text-3xl font-semibold text-black">{section.title.split(':')[1]}</h4>
              <div>
                {section.title.match(/Section 0(4|5|6|7)/) && (
                  <figure className="w-full md:w-64 float-right ml-6 mb-4">
                    <img 
                      src={getOptimizedImageUrl(
                        section.title.includes("Section 04") 
                          ? "https://i.pinimg.com/1200x/3e/09/76/3e0976235d0db25a0bed84f6df9a0a3f.jpg" 
                          : section.title.includes("Section 05")
                          ? "https://i.pinimg.com/736x/dc/b5/cf/dcb5cf4c9b507d3a57a8b4f466984ace.jpg"
                          : section.title.includes("Section 06")
                          ? "https://i.pinimg.com/736x/59/d1/34/59d13493ec9c363a6e9216d0818f8b41.jpg"
                          : "https://i.pinimg.com/736x/63/35/66/633566ec001678599fc9db142a4dc912.jpg",
                        600
                      )}
                      alt={section.title.split(':')[1]?.trim() || "Image"}
                      className="w-full h-auto aspect-square object-cover rounded-lg shadow-lg"
                      referrerPolicy="no-referrer"
                    />
                    <figcaption className="text-[10px] text-gray-500 mt-2 font-mono tracking-wider uppercase">
                      — {section.title.includes("Section 04") ? "Ancient frescoes" : section.title.includes("Section 05") ? "Ancient inscriptions" : section.title.includes("Section 06") ? "Lion's Paw Platform" : "Summit palace view"}.
                    </figcaption>
                  </figure>
                )}
                <p className="text-[#2d2d2d]/80 leading-relaxed font-light whitespace-pre-line">{section.body}</p>
              </div>
            </div>
          </section>
        ))}
      </div>
    </div>
  );
};

export default AboutSigiriya;
