import React from 'react';
import { Language } from '../types';

interface AboutMirissaProps {
  language: Language;
}

const AboutMirissa: React.FC<AboutMirissaProps> = ({ language }) => {
  const content = {
    title: language === 'EN' ? "Complete Travel Guide — Mirissa" : "සම්පූර්ණ සංචාරක මාර්ගෝපදේශය — මිරිස්ස",
    subtitle: language === 'EN' ? "Sri Lanka's Whale Watching Capital — Where the Deep Ocean Begins at the Shore" : "ශ්‍රී ලංකාවේ තල්මසුන් නැරඹීමේ අගනුවර — ගැඹුරු සාගරය වෙරළෙන් ආරම්භ වන ස්ථානය",
    description: language === 'EN' ? "Matara District, Southern Province • Beach & Wildlife destination • Open year-round • 35 km east of Galle" : "මාතර දිස්ත්‍රික්කය, දකුණු පළාත • වෙරළ සහ වනජීවී ගමනාන්තය • වසර පුරා විවෘතයි • ගාල්ලේ සිට කි.මී. 35 ක් නැගෙනහිරින්",
    sections: [
      {
        title: language === 'EN' ? "Section 01: Introduction — Why Mirissa Matters" : "01 වන කොටස: හැඳින්වීම — මිරිස්ස වැදගත් වන්නේ ඇයි",
        body: "Mirissa is, without question, one of the most captivating places on Sri Lanka's entire southern coastline. Situated on the Matara District coast approximately 35 kilometres east of Galle, this small beach town has earned a reputation that extends far beyond its modest size — and that reputation rests on two distinct but equally compelling foundations. The first is its beach: a wide, golden crescent of sand backed by swaying coconut palms, with warm and generally swimmable water and a laid-back atmosphere that has drawn independent travellers for decades. The second, and increasingly the dominant reason people make the journey here, is the whale watching. Mirissa sits at the southern tip of the island at a point where the ocean floor drops sharply into the deep waters of the Indian Ocean, and it is from this small harbour that some of the finest blue whale watching experiences in the world begin.\n\nThese two identities — beach town and wildlife gateway — sit side by side in Mirissa without any obvious contradiction. The village is small enough that both are accessible within minutes of wherever you happen to be staying, and the combination of a morning on a whale watching boat followed by an afternoon on the beach followed by a sunset drink on the headland is, for many visitors, the perfect day. It is a formula that has kept people coming back to Mirissa for years, and one that continues to define the particular character of this corner of the southern coast.\n\nMirissa is younger and slightly less polished than Unawatuna to its west, and this rawness is part of its appeal. The restaurant strip has a casual energy, the accommodation leans toward guesthouses and small boutique properties rather than large resorts, and the pace of life along the beach road slows to something approaching the unhurried rhythms of the fishing community that has always been at the heart of this place. Development has accelerated in recent years, but Mirissa has retained enough of its original character to still feel like a genuine discovery rather than a managed attraction."
      },
      {
        title: language === 'EN' ? "Section 02: History — A Fishing Harbour That the World Found" : "02 වන කොටස: ඉතිහාසය — ලෝකය සොයාගත් ධීවර වරායක්",
        body: "Like most of the villages along Sri Lanka's southern coast, Mirissa began as a modest fishing settlement, its community organised around the rhythms of the sea and the seasonal patterns of fish migration that have shaped coastal life here for centuries. The name Mirissa is believed to derive from an old Sinhala term, and the area was known to the ancient inhabitants of the region long before any colonial presence arrived on the island. Fishing remains a deeply embedded part of local identity, and the harbour at the western end of the bay continues to function as a working fishing port alongside its more recent role as the departure point for whale watching excursions.\n\nThe modern tourism story of Mirissa follows a pattern common to several of Sri Lanka's southern beaches. Independent travellers — backpackers following the coastal trail that had been established through Hikkaduwa, Unawatuna, and Weligama — began stopping at Mirissa in the late 1980s and through the 1990s, drawn by the beauty of the bay and the relative absence of the development that was already transforming beaches further west. Small guesthouses appeared, then restaurants, then the first dive and snorkelling operators, and gradually a recognisable tourism infrastructure took shape without ever quite losing the sense of informality that had attracted people in the first place.\n\nThe discovery that Mirissa was positioned within striking distance of one of the world's most productive blue whale feeding grounds transformed the town's international profile. As word spread — initially through travel forums and guidebooks, later through social media and wildlife documentaries — Mirissa became specifically associated with blue whale sightings, and this association drew a new category of visitor who might not otherwise have prioritised a small Sri Lankan beach town. The whale watching industry that has developed around this reputation is now the single most economically significant tourism activity in the area, though it has also brought with it questions about responsible practice that the community and operators continue to navigate.\n\n\"Standing at the bow of a boat as a blue whale surfaces thirty metres ahead of you — the largest animal that has ever lived on this planet — is an encounter with scale and wildness that no photograph fully prepares you for.\""
      },
      {
        title: language === 'EN' ? "Section 03: The Beach — Understanding the Bay" : "03 වන කොටස: වෙරළ — බොක්ක අවබෝධ කර ගැනීම",
        body: "The main beach at Mirissa runs for approximately one kilometre in a gently curved arc, with Parrot Rock — a small rocky islet accessible by wading at low tide — sitting at its western end and a forested headland marking the eastern boundary of the bay. The sand is golden and fine, the water a clear tropical blue-green, and the palm trees that lean over the upper beach provide pools of shade that make the midday heat manageable even in the hottest months. By the standards of Sri Lanka's southern coast, it is a beautiful beach, and its relative width and gentle gradient make it suitable for a broad range of visitors.\n\nUnlike Unawatuna, which is protected by a substantial offshore reef, Mirissa's bay is more directly exposed to the open ocean, and this means the surf conditions here can vary more significantly with the season and the swell direction. During the dry season from November through April the water is generally calm and swimming is comfortable throughout the bay. During the monsoon months from May through October the sea becomes rougher and swimming requires more caution, with stronger currents developing particularly toward the headlands at either end of the bay. The beach does not have lifeguards, and the surf is not suitable for inexperienced swimmers during rougher periods.\n\nParrot Rock at the western end of the beach is one of Mirissa's most photographed features and one of its most enjoyable. At low tide you can wade out to the rock across a shallow sandy channel and climb to its small summit, which provides a sweeping view back over the bay and the coastline stretching westward toward Weligama. A small shrine sits at the top, and the rock is a popular spot for watching both sunrise and sunset depending on the time of year. The eastern headland, reached by a short path from the far end of the beach, offers similarly expansive views and is a favourite spot for travellers seeking a quiet place to sit above the water away from the activity of the beach below."
      },
      {
        title: language === 'EN' ? "Section 04: Whale Watching — The Blue Whales of the Deep South" : "04 වන කොටස: තල්මසුන් නැරඹීම — ගැඹුරු දකුණේ නිල් තල්මසුන්",
        body: "The waters off Mirissa are part of one of the most productive marine wildlife zones in the entire Indian Ocean. The continental shelf drops away rapidly just south of the Sri Lankan coastline, creating deep-water conditions close to shore that support extraordinary concentrations of marine life. Blue whales — the largest animals ever to have lived on Earth, reaching lengths of up to 30 metres and weights of up to 200 tonnes — are present in these waters year-round, though sightings are most reliable between November and April when the sea is calmest and the whales are most consistently found in the feeding grounds accessible from Mirissa harbour.\n\nGoing out on a whale watching excursion from Mirissa is an experience that operates on a different emotional register from most wildlife encounters. Blue whales are so vast that the scale of the animal does not fully register until you are in the water beside one. When a blue whale surfaces close to the boat — its back rising slowly from the water like a grey-blue island, its exhalation sending a column of spray six metres into the air, its tail fluke lifting clear of the surface as it dives — the silence that falls over a boatload of people in that moment is involuntary. It is not something that requires narration or assistance. The animal simply demands complete attention.\n\nBeyond blue whales, the waters off Mirissa regularly produce sightings of sperm whales, fin whales, Bryde's whales, and multiple dolphin species including spinner dolphins, which often appear in large, acrobatic pods of hundreds of animals riding the bow wave of the boat. Blue whales and spinner dolphins sighted in the same excursion are not unusual, and on exceptional days the waters south of Mirissa can produce sightings that even experienced marine wildlife guides describe as remarkable. There are no guarantees in wild animal encounters, but the probability of seeing blue whales from Mirissa during the peak season is among the highest of any shore-based whale watching location in the world.\n\nChoosing a responsible operator\nThe rapid growth of the whale watching industry at Mirissa has brought with it concerns about boat crowding around animals and harassment of whales. Choose operators who commit to maintaining safe distances from whales, limiting time spent near any individual animal, and who carry a qualified marine naturalist on board rather than simply a boat captain.\n\nTrips depart from Mirissa harbour between 6:00 and 7:00 AM and typically last four to six hours. Take motion sickness medication the night before if you are at all susceptible — the open ocean crossing can be rough even on calm days.\n\nBring sun protection, a light layer for the boat, and more water than you think you will need. Binoculars are worthwhile if you have them."
      },
      {
        title: language === 'EN' ? "Section 05: Surfing — Riding the Southern Swell" : "05 වන කොටස: රළ මත ලිස්සා යාම — දකුණු රළ මත ලිස්සා යාම",
        body: "While Mirissa is not as celebrated a surf destination as nearby Weligama or Arugam Bay on the east coast, the beach does produce rideable waves during certain periods and has a small but loyal surfing community. The western end of the bay, near Parrot Rock, produces the most consistent break and is generally considered beginner to intermediate territory — waves that are approachable enough for those learning the sport but with enough power to satisfy more experienced riders looking for a fun, uncomplicated session. The reef break near the eastern headland is more challenging and less predictable.\n\nThe best surfing conditions at Mirissa coincide with the shoulder season — the period just before and just after the main southwest monsoon when the swell is running but the sea has not yet reached its roughest. April and May, as the monsoon approaches, and October and November, as it retreats, are the months when the waves at Mirissa are most consistently interesting. Several local surf schools operate from the beach and offer lessons and board rentals at reasonable rates. For travellers who have not surfed before but are curious, Mirissa offers a gentle and non-intimidating environment in which to try.\n\nIt is worth noting that the best whale watching season and the best surf season at Mirissa do not significantly overlap — the calm dry-season water that is ideal for whale watching is less productive for surfing. This is not a problem for most visitors, who are unlikely to be prioritising both activities simultaneously, but it is useful context if you are planning your trip around specific experiences. For pure surfing, the beach at Weligama, roughly fifteen kilometres to the west, offers more consistent and better-shaped waves across a longer season and is considered one of the best beginner surf spots in all of Asia."
      },
      {
        title: language === 'EN' ? "Section 06: Food and Nightlife — Eating and Evenings in Mirissa" : "06 වන කොටස: ආහාර සහ රාත්‍රී ජීවිතය — මිරිස්සේ ආහාර සහ සන්ධ්‍යාවන්",
        body: "Mirissa's restaurant scene is concentrated along the beach road and the lanes immediately behind the shore, and it reflects the eclectic, international character of the traveller community that passes through. Seafood is the undisputed centrepiece of the local culinary offer — fresh catches come directly off the boats at the harbour and onto the grills of the beachfront restaurants within hours, and the quality and freshness of the fish and shellfish at even modest establishments is genuinely impressive. Grilled barracuda, garlic butter prawns, devilled cuttlefish, and whole red snapper baked in banana leaves are among the dishes that appear repeatedly on menus and that consistently deliver.\n\nBeyond the seafood, Mirissa's restaurant strip offers Sri Lankan rice and curry, wood-fired pizza, fresh pasta, falafel wraps, smoothie bowls, and a range of Western breakfast options that have become standard equipment along the backpacker trail. The quality varies considerably, and the most reliable strategy is to eat where the locals eat — the small curry houses and short-eats shops on the lanes behind the beach offer far more authentic and significantly cheaper food than the tourist-facing restaurants on the main strip, and the rice and curry served from large clay pots at a local lunch spot is an experience worth prioritising over any amount of fusion cuisine.\n\nThe evening atmosphere at Mirissa is livelier and younger than at Unawatuna, with several beach bars drawing crowds of travellers for sundowner drinks that drift into late-night music sessions. The famous Mirissa beach parties — informal gatherings that developed organically around a few particular spots — have become a fixture of the southern coast social scene during peak season, with fire dancers, reggae music, and the kind of loosely organised festivity that characterises the better beach bars of Southeast Asia. For those who prefer a quieter evening, the eastern end of the beach and the guesthouses set back from the main strip offer a more peaceful alternative."
      },
      {
        title: language === 'EN' ? "Section 07: Where to Stay — Accommodation in Mirissa" : "07 වන කොටස: නවාතැන් — මිරිස්සේ නවාතැන්",
        body: "Accommodation in Mirissa spans a wide range of styles and price points, from simple fan rooms in family guesthouses tucked into the coconut groves behind the beach to comfortable boutique hotels with pools, sea-view terraces, and carefully designed rooms that would not look out of place in a travel magazine. The village is compact enough that virtually all accommodation is within walking distance of both the beach and the harbour, and the distinction between beachfront and village-side properties is less significant here than at larger resorts.\n\nThe most popular accommodation sits in the middle of the market — small guesthouses and boutique properties with air conditioning, decent bathrooms, and either garden or partial sea views, at rates that represent good value relative to comparable quality at more developed destinations. Many of these properties are family-run, which tends to translate into attentive and personal service, home-cooked breakfasts on the terrace, and owners who are genuinely helpful with whale watching bookings, tuk-tuk arrangements, and itinerary advice. This personal quality of service is one of Mirissa's distinct advantages over larger, more anonymised beach resorts.\n\nFor travellers on a tight budget, the lanes behind the beach road offer a selection of very inexpensive guesthouses where basic rooms with fans and shared facilities can be found at rates that make extended stays financially comfortable. Mirissa is also increasingly home to a small number of higher-end boutique properties positioned in the hills above the bay, offering elevated views over the coast and a degree of seclusion that the beachfront cannot provide. These hilltop options are particularly beautiful in the early morning, when the bay below is still in shadow and the sun comes up over the eastern headland in a slow progression of colour."
      },
      {
        title: language === 'EN' ? "Section 08: Practical Information — What You Need to Know" : "08 වන කොටස: ප්‍රායෝගික තොරතුරු — ඔබ දැනගත යුතු දේ",
        body: "Distance from Colombo: ~150 km (3–3.5 hrs)\nDistance from Galle: ~35 km (45 min)\nWhale watching season: Nov – April (peak)\nWhale watching cost: USD 35 – 60 per person\nBeach entry: Free, open 24 hrs\nNearest town: Matara (15 km east)\n\nThe beach at Mirissa is a public space with no entrance fee. The main road that runs parallel to the beach carries motorcycle and tuk-tuk traffic throughout the day and can feel congested during peak season. Walking along the beach itself rather than the road is almost always the more pleasant option for getting from one end of the village to the other. ATMs are available in Mirissa itself and in Matara, and while many restaurants and guesthouses accept cards, having cash available is advisable particularly for local shops, market vendors, and tuk-tuk fares.\n\nThe nearest public hospital is in Matara, approximately 15 kilometres to the east. Mobile coverage in Mirissa is generally good with all major Sri Lankan networks. The village has reliable electricity and wifi is widely available at guesthouses and restaurants, though connection speeds can be inconsistent during peak hours. Tuk-tuks are the primary local transport option and are available throughout the village — agree on a fare before boarding or use a ride-hailing app if you have a local SIM.\n\nVisitor tips:\nBook whale watching trips at least one or two days in advance during peak season (December to March). Same-day bookings are sometimes possible but space on reputable boats fills quickly.\n\nThe sea at Mirissa has no lifeguards. Be cautious during rougher conditions and pay attention to local advice about currents, particularly near the headlands at either end of the bay.\n\nDress modestly when walking through the village away from the beach — swimwear is appropriate at the shore but not in local shops or at places of worship.\n\nSunrise at Parrot Rock is one of the finest free experiences Mirissa offers. Set your alarm for thirty minutes before dawn, walk to the western end of the beach, and wade out to the rock — you will likely have it entirely to yourself."
      },
      {
        title: language === 'EN' ? "Section 09: Best Time to Visit — Season, Sea, and Wildlife" : "09 වන කොටස: සංචාරය කිරීමට හොඳම කාලය — කාලගුණය, මුහුද සහ වනජීවීන්",
        body: "The best time to visit Mirissa depends on what you have come for, and the answer differs somewhat depending on whether whale watching or beach relaxation is your primary motivation. For whale watching, the peak season runs from November through April, with December through March representing the window of most reliable sightings and calmest sea conditions for the boat crossing. January and February are widely regarded as the optimum months — the sea is settled, visibility is good, the whales are present in consistent numbers, and the weather on land is warm and reliably sunny. These are also the busiest months for tourism across the southern coast, so accommodation should be booked well in advance.\n\nFor the beach itself, the dry season on the southern coast — broadly November through April — produces the most reliably pleasant conditions, with warm days, low humidity, and the calm, clear water that makes swimming, snorkelling, and simply lying on the sand most enjoyable. The water temperature remains warm year-round, hovering between 27 and 30 degrees Celsius, so cold water is never a concern. The primary variable is wave height and current strength, which are at their mildest during the dry season and most significant during the southwest monsoon from May through October.\n\nThe shoulder months of October to November and late April to May offer a compelling middle ground. Visitor numbers are lower, accommodation prices drop noticeably, and the landscape is dramatically green from the monsoon rains. The whale watching in November is often excellent as the season opens, and the beaches are far less crowded than at the height of peak season. For travellers with flexible schedules who are comfortable with some meteorological unpredictability, these months represent perhaps the best overall value at Mirissa — the possibility of good whale sightings, an uncrowded beach, lower prices, and the particular beauty of the southern coast in the transition between monsoon and dry season."
      },
      {
        title: language === 'EN' ? "Section 10: Getting There — Reaching Mirissa" : "10 වන කොටස: ගමන් මාර්ගය — මිරිස්සට ළඟා වීම",
        body: "Mirissa is located on the main southern coastal road between Galle and Matara, which makes it straightforward to reach by a variety of means. The most scenic approach from Colombo is by train — the Coastal Line runs to Weligama, the nearest station to Mirissa, from where a short tuk-tuk ride of approximately five kilometres delivers you to the beach. The train journey from Colombo Fort to Weligama takes roughly three hours and follows the coast for much of its length, offering views of lagoons, fishing boats, and the open ocean that are among the most beautiful of any train journey in Sri Lanka. Trains depart multiple times daily and fares are inexpensive, though first and second class seats should be reserved in advance during peak season.\n\nBy road from Colombo, the Southern Expressway provides a fast connection to the Matara exit, from where the old coast road leads westward to Mirissa in approximately fifteen minutes. The total driving time from Colombo is around two and a half to three hours depending on traffic. Private car hire with a driver, arranged through your guesthouse or a tour operator in Colombo, is the most comfortable and flexible road option and allows you to stop along the way — at the Galle Fort, at Hikkaduwa's coral reef, or at any of the small beach towns that line the southern coast between the city and Mirissa.\n\nMirissa sits at an excellent position for onward travel in either direction along the coast. Weligama, renowned for its surf and its gentle bay, is just fifteen kilometres to the west and makes an easy half-day excursion. Matara, the largest city on the southern coast, is fifteen kilometres to the east and serves as a transport hub for buses continuing to Tangalle, Tissamaharama, and the far southeastern coast. The ancient rock fortress of Mulkirigala, an undervisited but deeply impressive counterpart to Sigiriya, is located approximately 30 kilometres inland from Mirissa and can be visited as a rewarding day trip from the village."
      },
      {
        title: language === 'EN' ? "Section 11: Nearby Attractions — Beyond the Bay" : "11 වන කොටස: අවට ආකර්ෂණීය ස්ථාන — බොක්කෙන් ඔබ්බට",
        body: "Weligama, the closest coastal town to Mirissa's west, is worth at least a half-day visit and for surf enthusiasts may be worth dedicating significantly more time to. The bay at Weligama is one of the finest beginner surf spots in all of Asia — wide, consistent, and gentle enough for complete novices while still offering enough wave energy to be engaging. Dozens of surf schools line the beach and the instruction is generally very good. The Weligama bay also has its own distinct character, calmer and more residential than Mirissa, and the fish market at the harbour on the western end of town is one of the most vivid and fragrant market experiences on the entire southern coast.\n\nMulkirigala Rock Temple, located approximately 30 kilometres north of Mirissa near the town of Beliatta, is one of the most dramatically situated and genuinely moving religious sites in Sri Lanka that most visitors never hear about. A series of Buddhist cave temples cut into and built upon a towering granite inselberg — smaller than Sigiriya but in some ways more intimate — contains ancient frescoes, reclining Buddhas, and inscriptions of extraordinary historical significance. The climb to the summit temples passes through jungle and offers sweeping views across the flat southern lowlands. Unlike the main Cultural Triangle sites, Mulkirigala receives relatively few foreign visitors, and the experience of exploring its temple chambers in something close to solitude is remarkable.\n\nFor those with an interest in sea turtles, several conservation projects operate along the southern coast near Mirissa and offer visitors the chance to observe nesting turtles, assist with hatchling releases, and learn about the protection of the five turtle species that nest on Sri Lanka's beaches. These projects vary considerably in quality and ethical standards, and it is worth researching specific operators before committing. The best programmes prioritise the welfare of the turtles over visitor entertainment and operate with the involvement of local communities. A release of sea turtle hatchlings into the ocean at dusk — watching the tiny animals navigate their way down the sand and into the waves — is among the most affecting wildlife experiences available anywhere on the southern coast."
      },
      {
        title: language === 'EN' ? "Section 12: Final Thoughts — What Mirissa Leaves With You" : "12 වන කොටස: අවසාන අදහස් — මිරිස්ස ඔබ සමඟ ඉතිරි කරන්නේ කුමක්ද",
        body: "There is a particular quality to Mirissa that is hard to articulate but easy to recognise once you have experienced it. It is not the most pristine beach on the southern coast, nor the most developed, nor the most historically significant. What it has is a combination of natural drama and easy living that sits together in a way that feels genuinely fortunate — the kind of place that seems to have been designed for the specific purpose of making people feel well.\n\nThe memory of a morning on the water — the harbour lights still visible behind you as the boat heads south into the open ocean, the first whale surfacing in the distance with a sound you feel as much as hear — stays with people for the rest of their lives. The afternoon on the beach that follows, with the particular fatigue of having been on the ocean all morning, the cold drink, the late lunch of fresh fish, the sun going down behind Parrot Rock — this too is something people return to in their minds long after they have left.\n\nMirissa is not a place that announces itself with monuments or UNESCO plaques. Its significance is quieter and more personal — the feeling of being at the very edge of a great ocean, at the bottom of an island that has been welcoming travellers for thousands of years, in a small village that has somehow held onto its character through decades of being discovered and rediscovered. That is enough. It is, in fact, more than enough."
      }
    ]
  };

  return (
    <div className="space-y-20">
      <header className="mb-20 border-b border-[#5A5A40]/10 pb-12">
        <span className="text-[11px] uppercase tracking-[0.5em] text-[#5A5A40]/60 font-medium">Coastal Destination</span>
        <h1 className="text-5xl md:text-7xl font-light tracking-tighter mt-6 mb-6 text-[#2d2d2d]">{content.title}</h1>
        <h2 className="text-2xl font-light text-[#2d2d2d]/70">{content.subtitle}</h2>
        <p className="text-sm text-[#2d2d2d]/50 mt-4 max-w-xl">{content.description}</p>
      </header>
      
      <div className="space-y-20">
        {content.sections.map((section, index) => (
          <section key={index} className="grid md:grid-cols-[200px,1fr] gap-8">
            <h3 className="text-[11px] uppercase tracking-[0.3em] text-[#5A5A40]/50 pt-2">{section.title.split(':')[0]}</h3>
            <div className="space-y-4">
              <h4 className="text-2xl md:text-3xl font-semibold text-black">{section.title.split(':')[1]}</h4>
              <p className="text-[#2d2d2d]/80 leading-relaxed font-light whitespace-pre-line">{section.body}</p>
            </div>
          </section>
        ))}
      </div>
    </div>
  );
};

export default AboutMirissa;
