import React from 'react';
import { Language } from '../types';

interface AboutArugamBayProps {
  language: Language;
}

const AboutArugamBay: React.FC<AboutArugamBayProps> = ({ language }) => {
  const content = {
    title: language === 'EN' ? "Complete Travel Guide — Arugam Bay" : "සම්පූර්ණ සංචාරක මාර්ගෝපදේශය — ආරුගම් බොක්ක",
    subtitle: language === 'EN' ? "Sri Lanka's Surf Capital — The East Coast's Wildest and Most Beloved Shore" : "ශ්‍රී ලංකාවේ රළ මත ලිස්සා යාමේ අගනුවර — නැගෙනහිර වෙරළේ වනගතම සහ ආදරණීය වෙරළ තීරය",
    description: language === 'EN' ? "Ampara District, Eastern Province • World-class surf destination • Season: May – October • 320 km from Colombo" : "අම්පාර දිස්ත්‍රික්කය, නැගෙනහිර පළාත • ලෝක මට්ටමේ රළ මත ලිස්සා යාමේ ගමනාන්තයක් • කාලය: මැයි – ඔක්තෝබර් • කොළඹ සිට කි.මී. 320 යි",
    sections: [
      {
        title: language === 'EN' ? "Section 01: Introduction — Why Arugam Bay Matters" : "01 වන කොටස: හැඳින්වීම — ආරුගම් බොක්ක වැදගත් වන්නේ ඇයි",
        body: "Arugam Bay is unlike anywhere else in Sri Lanka. Situated on the country's remote eastern coast in the Ampara District, this small crescent-shaped bay has earned a global reputation entirely out of proportion with its modest size and infrastructure — a reputation built not on luxury or convenience but on the quality of its surf, the wildness of its surrounding landscape, and the particular brand of laid-back freedom that only the most genuinely off-the-beaten-track destinations can produce. For surfers, Arugam Bay is a pilgrimage. For travellers seeking the eastern coast's very different character from the developed south, it is a revelation.\n\nThe bay's famous right-hand point break — known simply as Main Point or A-Bay Point — is ranked among the top surfing spots in the world and consistently draws professional surfers and travelling wave-hunters from every surfing nation during the season. But Arugam Bay is far more than a surf spot. The surrounding region encompasses extraordinary wildlife in Kumana and Lahugala national parks, ancient Buddhist temples predating the common era, lagoons filled with wading birds and crocodiles, empty beaches of white sand that see almost no visitors, and a community of Tamil and Muslim residents whose cultures and cuisines add a dimension entirely absent from the Sinhalese-majority south.\n\nThe experience of arriving at Arugam Bay for the first time — after the long drive across the dry zone interior, through the flat scrubland and the elephant country, emerging suddenly onto this eastern shore with its different light and its different air and the long lines of swell coming in off the Indian Ocean — is one of the most distinctive arrival experiences in Sri Lanka. The journey itself tells you that you have left the tourist trail behind and entered something more authentic, more demanding, and more rewarding."
      },
      {
        title: language === 'EN' ? "Section 02: History — A Bay That the War Kept Hidden" : "02 වන කොටස: ඉතිහාසය — යුද්ධය විසින් සඟවා තිබූ බොක්කක්",
        body: "Arugam Bay's history as a surf destination is inseparable from the history of Sri Lanka's civil conflict. The bay was discovered by travelling surfers in the late 1970s and early 1980s, when a handful of pioneering wave-hunters made the long journey across the island and found a right-hand point break of exceptional quality in a bay that the rest of the world had never heard of. Word spread slowly through the global surfing community, and through the 1980s a small trickle of surfers and independent travellers began making the journey, establishing the first guesthouses and creating the rudimentary tourism infrastructure that still characterises much of the village today.\n\nThe civil war between the Sri Lankan government and the Tamil Tigers, which dominated the country's politics and geography from the early 1980s until 2009, effectively closed the eastern coast to tourism for long periods. Arugam Bay sat in a zone of conflict and insecurity, and the trickle of visitors that had been building through the 1980s all but dried up through the 1990s and the early 2000s. The local community endured decades of displacement, fear, and economic stagnation that the brief surfing season could do little to alleviate. The 2004 Indian Ocean tsunami, which struck the eastern coast with enormous force, added further devastation to a community already exhausted by years of conflict.\n\nThe end of the civil war in 2009 opened the east to tourism for the first time in a generation, and the transformation of Arugam Bay in the years that followed has been rapid and dramatic. Visitors arrived in numbers that the village had never seen, guesthouses multiplied, restaurants opened, and the surf scene that had existed only in the memories of those who had visited before the war was rebuilt from almost nothing. Today Arugam Bay is Sri Lanka's most internationally celebrated surf destination and one of the east coast's primary economic engines — a remarkable trajectory for a village that spent twenty years largely invisible to the outside world.\n\n\"Arugam Bay spent decades hidden by war and found by the ocean — the swell was always coming, and when the peace finally arrived, the surfers were not far behind.\""
      },
      {
        title: language === 'EN' ? "Section 03: The Surf — Main Point and Beyond" : "03 වන කොටස: රළ මත ලිස්සා යාම — ප්‍රධාන ස්ථානය සහ ඉන් ඔබ්බට",
        body: "The surf at Arugam Bay is the reason the village exists on the global travel map, and Main Point — the right-hand point break that peels along the southern end of the bay — is the centrepiece of everything. When the swell is running properly, typically between June and September at the height of the eastern season, Main Point produces long, walling waves that can run for 200 metres or more before they close out on the inside. These are not hollow, dramatic waves in the manner of a reef break — they are rolling, workable, high-quality point break waves that allow surfers to link multiple turns, practice manoeuvres at length, and simply enjoy the pleasure of a long ride in warm water. On the right day, the queue in the water is international and the standard is high.\n\nMain Point works best on a medium to large swell from the southeast, which is precisely what the trade winds deliver to the eastern coast during the May to October window. The peak of the surf season — roughly July and August — produces the most consistent and powerful conditions, and it is during these weeks that the village fills with surfers who have timed their trip specifically around the forecast. September and October offer less power but more variety and fewer people in the water, and for intermediate surfers these months can actually produce more enjoyable sessions than the competitive peak.\n\nBeyond Main Point, the Arugam Bay area has a collection of additional surf breaks spread along the coast in both directions that cater to different skill levels and different swell conditions. Whiskey Point, located a few kilometres to the north of the main bay, is a more forgiving right-hander that is widely recommended for beginners and intermediate surfers. Pottuvil Point, to the north near the lagoon, is a long and powerful wave that works on bigger swells and rewards experienced surfers willing to make the journey. Elephant Rock, further south along the coast, is a powerful and more challenging break that is largely the preserve of advanced surfers. Multiple surf schools operating from the main bay offer lessons and board rentals for visitors at all skill levels, and the instruction quality at the better schools is genuinely good.\n\nSurf essentials\nBoard rentals are widely available in the village at reasonable daily and weekly rates. If you are particular about your equipment, bringing your own board is worthwhile — the rental stock is functional but not always well maintained.\n\nThe reef at Main Point is shallow in sections. Reef booties are worth considering for less experienced surfers who may fall more frequently in the impact zone.\n\nRespect the surf etiquette at Main Point — the peak can be crowded during the height of season and the local surfers have priority. Being courteous and patient in the water is both the right thing to do and the fastest route to being welcomed into the lineup."
      },
      {
        title: language === 'EN' ? "Section 04: The Beach — Life Along the Bay" : "04 වන කොටස: වෙරළ — බොක්ක දිගේ ජීවිතය",
        body: "The main beach at Arugam Bay runs for approximately two kilometres along the arc of the bay, with the surf point at its southern end and the lagoon mouth at its northern end. The sand is pale gold and generally wide, though it narrows noticeably toward the southern end near Main Point where the reef comes closer to shore. The water is warm, clear, and a vivid tropical blue on calm days, and the absence of significant commercial development along the beachfront gives the shore a natural, unmanicured quality that travellers who have grown tired of the heavily developed southern beaches find immediately refreshing.\n\nSwimming at Arugam Bay requires some awareness of conditions. During the peak surf season the bay can be producing significant swell that makes casual swimming in the surf zone inadvisable for non-surfers, and the currents around the point can be deceptive. The calmer, more protected section of the bay toward the northern end — away from the break — is generally the most suitable for non-surfer swimmers. Outside of the peak surf months, particularly in April and May at the beginning of the season, the bay can be very calm and excellent for swimming. The water temperature is warm year-round, consistently around 27 to 30 degrees Celsius.\n\nThe pace of life on the beach at Arugam Bay is unhurried in a way that feels genuinely earned rather than performed. The morning is defined by the sound of surfboards being waxed and the sight of surfers paddling out in the early light. The afternoon brings heat, hammocks, card games on guesthouse terraces, and the particular drowsy contentment of people who have been in the water since dawn. The evening brings the village to life along the beach road — the smell of cooking fires, the sound of music drifting from the beach bars, the gathering of travellers who have come from every surfing nation on earth and found themselves in the same small bay on the eastern edge of an island in the Indian Ocean."
      },
      {
        title: language === 'EN' ? "Section 05: Wildlife — Elephants, Leopards, and the Kumana Wetlands" : "05 වන කොටස: වනජීවීන් — අලි ඇතුන්, දිවියන් සහ කුමන තෙත්බිම්",
        body: "One of Arugam Bay's most distinctive qualities — and one that separates it clearly from every other surf destination in Sri Lanka — is its proximity to some of the island's most spectacular wildlife. The village sits at the edge of a landscape of lagoons, dry-zone jungle, and ancient tanks that supports populations of animals rarely encountered anywhere else on the island. Simply driving the roads around Arugam Bay in the early morning or late afternoon will frequently produce sightings of wild elephants grazing in the scrubland, monitor lizards crossing the road, peacocks displaying in the open ground, and a remarkable diversity of waterbirds working the lagoon edges.\n\nKumana National Park, located approximately 35 kilometres south of Arugam Bay along the coast road, is one of Sri Lanka's most important and least crowded wildlife reserves. The park encompasses a vast coastal wetland system — mangrove lagoons, brackish lakes, and river deltas — that serves as a breeding ground for an extraordinary range of waterbirds. From May to July, Kumana hosts one of the largest water bird colonies in Asia, with painted storks, open-billed storks, night herons, spoonbills, cormorants, and dozens of other species nesting in dense concentrations in the mangrove trees. The park also supports populations of elephants, leopards, sloth bears, crocodiles, and sambar deer. Safari jeeps can be arranged from Arugam Bay, and the relatively low visitor numbers at Kumana compared to Yala mean that wildlife encounters here often feel less pressured and more intimate.\n\nLahugala Kitulana National Park, a smaller reserve located approximately 15 kilometres west of Arugam Bay on the road toward Monaragala, is one of the most reliable places in Sri Lanka to observe wild elephants at close range. The park's central tank — an ancient irrigation reservoir that has existed since the early centuries of the common era — draws large herds of elephants to drink and bathe, particularly in the dry season months when the park's water sources are concentrated. Evening visits, when the light is low and the elephants move in large family groups through the shallow water, can produce encounters of extraordinary intimacy and beauty. Entry fees are modest and the park requires only a short detour from the main Arugam Bay access road."
      },
      {
        title: language === 'EN' ? "Section 06: Culture and Heritage — The Ancient East" : "06 වන කොටස: සංස්කෘතිය සහ උරුමය — පැරණි නැගෙනහිර",
        body: "The landscape around Arugam Bay is layered with history that most visitors, focused on the surf and the beach, never take the time to explore. The eastern province was one of the earliest settled regions of Sri Lanka, and the ancient irrigation tanks and Buddhist temple complexes that dot the interior predate many of the more celebrated ruins of the Cultural Triangle by centuries. Exploring this heritage requires effort and often a tuk-tuk or bicycle, but the rewards are considerable — not least because the absence of tourist crowds at these sites gives encounters with ancient Sri Lanka a quality of solitude that has long since vanished at Sigiriya or Polonnaruwa.\n\nThe Muhudu Maha Viharaya, a Buddhist temple located at the southern end of the bay near the lagoon, is one of the most historically significant sites in the immediate vicinity of Arugam Bay. According to tradition, it marks the landing point of Princess Viharamahadevi, whose son Dutugamunu would go on to become one of Sri Lanka's most celebrated ancient kings. The temple's setting — ancient stone Buddha statues and carved pillars at the edge of the lagoon, with the ocean visible beyond — has a profound serenity that contrasts sharply with the surf culture of the village a short distance away. The temple is an active place of worship and should be visited with appropriate respect for dress and behaviour.\n\nThe Pottuvil Lagoon, stretching northward from the bay toward the town of Pottuvil, is a significant cultural and ecological feature of the region. The lagoon is home to large populations of crocodiles, and boat trips through its mangrove channels offer close encounters with these ancient reptiles as well as superb birdwatching. The communities living around the lagoon — Tamil and Muslim fishing families whose way of life has changed little in essential character over generations — represent the cultural fabric of the eastern province, and the market at Pottuvil town gives a vivid window into the daily rhythms of a part of Sri Lanka that most visitors to the island never see."
      },
      {
        title: language === 'EN' ? "Section 07: Food — Eating on the Eastern Coast" : "07 වන කොටස: ආහාර — නැගෙනහිර වෙරළේ ආහාර",
        body: "The food at Arugam Bay is one of the village's genuine pleasures, and its character differs meaningfully from what you find on the southern coast. The eastern province's Tamil and Muslim heritage means that the culinary influences here are distinct — rice and curry with a Tamil flavour profile, roti and dhal of a style more closely related to the Indian subcontinent, kottu prepared with a different hand than in the south, and seafood cooked with spice combinations that are particular to the eastern coastal communities. Eating at the small local restaurants and short-eats shops that serve the resident community rather than the tourist strip is one of the most rewarding culinary decisions you can make at Arugam Bay.\n\nThe main beach road and the lanes around it are lined with guesthouse restaurants and beach cafes that cater to the international surfing and travelling crowd, offering a predictable but often genuinely good range of options — fresh grilled fish, prawn curries, pasta, pancakes, smoothie bowls, and strong coffee. Several of these establishments have been in operation for many years and have developed loyal followings among returning visitors. The freshness of the seafood here is outstanding — the fishing community working the lagoon and the open coast means that the fish on your plate was almost certainly in the water that same morning, and this shows clearly in the flavour.\n\nA few specific culinary experiences are worth seeking out at Arugam Bay. The crab curry served at several of the local Tamil-owned restaurants is exceptional — mud crabs from the lagoon prepared in a dark, intensely spiced gravy that is quite unlike anything available on the southern coast. String hoppers with dhal and coconut sambol served at a local spot for breakfast is the kind of simple, perfectly calibrated meal that stays in memory. And the wood-fired rotis available at small stalls in the early evening, eaten with a sweet tea while watching the sun go down over the lagoon behind the village, are among the small pleasures of Arugam Bay that cost almost nothing and mean everything."
      },
      {
        title: language === 'EN' ? "Section 08: Where to Stay — Accommodation at A-Bay" : "08 වන කොටස: නවාතැන් — ආරුගම් බොක්කේ නවාතැන්",
        body: "Accommodation at Arugam Bay ranges from the extremely basic to the surprisingly comfortable, with the majority of the village's guesthouses and boutique properties sitting in the affordable to mid-range band. The overall standard has improved markedly since the post-war reopening of the east, and while Arugam Bay will never compete with the polished hotel offerings of Colombo or the Maldives, the better properties here offer genuine comfort, personal service, and an atmosphere that more expensive and formally run establishments cannot replicate.\n\nThe most popular accommodation sits along and just behind the main beach road — small guesthouses and surf lodges where the rooms are simple but clean, the breakfasts are served on open terraces, and the owners can tell you exactly what the surf is doing and where to eat. Many of these properties are run by people who came to Arugam Bay as surfers themselves and never left, and this gives them a knowledge of the village and its surroundings that is invaluable for a first-time visitor. Board storage, surf advice, and informal surf trip organisation are standard offerings at most surf-focused guesthouses.\n\nA growing number of more design-conscious boutique properties have appeared in and around Arugam Bay in recent years, some of them set back from the village in the surrounding landscape of lagoons and palm trees and offering a quieter and more secluded base from which to explore the area. Several properties on the lagoon side of the village offer a particularly beautiful setting — waking up to the sight of the lagoon in the early morning light, with birds moving through the mangroves and the sound of the surf audible in the distance, is a genuinely restorative experience. Accommodation in Arugam Bay should be booked in advance for any visit during the peak surf season from June through September."
      },
      {
        title: language === 'EN' ? "Section 09: Practical Information — What You Need to Know" : "09 වන කොටස: ප්‍රායෝගික තොරතුරු — ඔබ දැනගත යුතු දේ",
        body: "Distance from Colombo: ~320 km (6–7 hrs)\nSurf season: May – October\nPeak surf months: July – September\nWater temperature: 27 – 30°C\nBoard rental (daily): ~LKR 1,500 – 3,000\nNearest hospital: Ampara General Hospital\n\nArugam Bay is a small village and cash is essential — ATMs are available in Pottuvil town, a few kilometres north of the bay, but reliability can be inconsistent and queues during peak season can be long. It is strongly advisable to carry sufficient cash from your last major city stop. Mobile coverage has improved significantly in recent years and most Sri Lankan networks provide reasonable data connectivity in the village, though speeds can be slow during busy periods.\n\nThe village has no traffic lights, few road markings, and a casual approach to road rules that is charming until it involves you. Bicycles and scooters are widely available for rent and are the most enjoyable way to explore the surrounding area, but exercise caution, particularly on the road north toward Pottuvil where sandy patches and potholes require attention. Elephants crossing the roads around Lahugala and in the national park areas are a genuine road hazard at night — driving after dark in the surrounding countryside should be done with great care and ideally avoided.\n\nVisitor tips\nThe village essentially closes during the off-season from November to April, when the southwest monsoon makes the east coast rough and most guesthouses and restaurants shut for the year. Always verify that your accommodation is open before making the long journey.\n\nBring any specialist items you need — surf equipment, medical supplies, quality sunscreen — from Colombo or a larger city. The village shop selection is limited and prices for imported goods are high.\n\nMosquitoes are present, particularly near the lagoon edges at dawn and dusk. Apply repellent consistently, particularly if staying in accommodation close to the water.\n\nRespect the local Muslim and Tamil communities. Arugam Bay village is culturally distinct from the Sinhalese Buddhist south. Dress modestly when away from the beach and be mindful of local religious observances and sensitivities."
      },
      {
        title: language === 'EN' ? "Section 10: Best Time to Visit — The Eastern Season" : "10 වන කොටස: සංචාරය කිරීමට හොඳම කාලය — නැගෙනහිර කාලගුණය",
        body: "The eastern coast of Sri Lanka operates on the opposite seasonal calendar from the south and west, and this is the single most important piece of planning information for any traveller considering Arugam Bay. The east coast's dry season runs from roughly May through October, driven by the southwest monsoon that brings rain to the western side of the island during exactly these months. When the south is wet, the east is dry — and vice versa. This means Arugam Bay's surf season and tourism season are concentrated between May and October, with the village largely closing down from November through April when the northeast monsoon delivers rain to the east coast and the swell from that direction makes surfing at Main Point far less productive.\n\nWithin the open season, the peak surf months of July through September bring the most consistent and powerful swells, the largest number of visiting surfers, the highest accommodation prices, and the most vibrant atmosphere in the village. June is an excellent month — the season is beginning, the swell is building, and the village has not yet reached its fullest population. October is equally appealing in the other direction — the crowds thin noticeably as the season winds down, prices drop, and the swell can still produce quality waves. For non-surfers who have come primarily for the wildlife, the beach, and the surrounding landscape, the shoulder months of May to June and October are often the most rewarding, combining reasonable surf conditions with more breathing room and better value.\n\nThe heat at Arugam Bay during the peak season is significant. The eastern coast receives full, direct sun with little shade relief, and temperatures regularly reach 32 to 35 degrees Celsius during the middle of the day. The sea breeze that picks up most afternoons provides some relief on the beach and in the water, but the midday hours are genuinely intense and most experienced visitors to the east coast structure their days accordingly — active in the early morning and late afternoon, slower in the middle of the day. Staying hydrated requires conscious effort, particularly if you are spending significant time in the surf."
      },
      {
        title: language === 'EN' ? "Section 11: Getting There — The Long Road to the East" : "11 වන කොටස: ගමන් මාර්ගය — නැගෙනහිරට දිගු ගමන",
        body: "Getting to Arugam Bay is part of the experience, and it is an experience that immediately sets it apart from the more accessible destinations on the southern coast. The village is approximately 320 kilometres from Colombo by road, and the journey takes between six and seven hours depending on the route and traffic conditions. There is no expressway to the east, and the roads crossing the interior of the island — through Monaragala and the dry zone — are narrower and slower than the southern highway network. This distance is precisely why Arugam Bay has retained its frontier quality despite growing international fame: the effort required to get here filters out the casual visitor and creates a community of people who have made a deliberate choice to come.\n\nThe most common route by road from Colombo follows the Southern Expressway to the Matara or Hambantota exit, then turns northward through the island's dry zone interior via Wellawaya or Monaragala before descending to the eastern coast. Alternatively, travellers coming from Kandy or the Cultural Triangle can cross the interior via Mahiyangana and Ampara, a route that passes through some of the island's most dramatic and least visited inland landscape. Private car hire with a driver, arranged from Colombo or from whichever destination you are coming from, is the most comfortable option and provides the flexibility to stop at points of interest along the way, including Lahugala National Park, which sits directly on the approach road.\n\nBy public transport, express buses operate between Colombo and Pottuvil — the town immediately north of Arugam Bay — several times daily, though journey times are longer than by private car and the overnight bus, while inexpensive, is not the most restorative way to begin a beach holiday. From Pottuvil, a short tuk-tuk ride delivers you to the bay. Travellers coming from the south can also take the train to Monaragala or hire transport from Ella or Tissamaharama, both of which are popular stops on the southern circuit and both of which are within a few hours of Arugam Bay by the interior roads. Domestic flights connecting Colombo to Batticaloa, the nearest airport to Arugam Bay, are available and reduce the journey significantly for those willing to pay the premium."
      },
      {
        title: language === 'EN' ? "Section 12: Nearby Attractions — The Wider Eastern World" : "12 වන කොටස: අවට ආකර්ෂණීය ස්ථාන — පුළුල් නැගෙනහිර ලෝකය",
        body: "Arugam Bay is an excellent base for exploring an eastern coastline that extends in both directions with remarkable variety. To the south, the road toward Kumana passes through a landscape of coastal jungle and empty beaches that sees almost no visitors — stretches of white sand backed by dense vegetation, accessible via sandy tracks from the main road, where the only footprints are those of nesting sea turtles and the occasional wading bird. These beaches are among the most pristine and least visited on the entire island, and for those willing to seek them out they offer a solitude and natural beauty that even the remoter spots of the southern coast cannot match.\n\nThe town of Batticaloa, located approximately 65 kilometres north of Arugam Bay, is the main urban centre of the eastern province and offers a window into the Tamil cultural life of the region that the beach village cannot provide. Batticaloa's lagoon is one of the largest on the island, and the town's famous singing fish — an acoustic phenomenon caused by molluscs or water conditions that produces a mysterious musical sound from the lagoon on certain nights — has been observed and documented since the earliest colonial accounts of the region. The town's Dutch fort, though less spectacularly preserved than Galle, retains its basic structure and provides historical context for the colonial history of the eastern coast.\n\nThe ancient city of Polonnaruwa, one of Sri Lanka's greatest historical treasures and a UNESCO World Heritage Site of the first order, can be reached from Arugam Bay in approximately three to four hours via the interior roads. For travellers who have not visited the Cultural Triangle and who are based on the eastern coast, Polonnaruwa makes an entirely feasible day trip and provides an encounter with the grand scale of medieval Sinhalese civilisation that complements rather than duplicates the Tamil and Muslim cultural heritage of the eastern province. The combination of an early departure, a morning at Polonnaruwa's extraordinary ruins, and a return to the bay in time for an evening surf session is demanding but completely achievable and deeply satisfying."
      },
      {
        title: language === 'EN' ? "Section 13: Final Thoughts — What Arugam Bay Gives You" : "13 වන කොටස: අවසාන අදහස් — ආරුගම් බොක්ක ඔබට ලබා දෙන දේ",
        body: "There is a freedom at Arugam Bay that is difficult to find anywhere else in Sri Lanka, and that is not simply a function of its remoteness or its surf. It is the freedom of a place that has not yet been entirely organised and packaged for consumption — where the day still has space in it for things to happen unexpectedly, where the person you meet at breakfast might take you somewhere extraordinary in the afternoon, where the wave you catch at the end of a long session turns out to be the best of the trip and nobody is around to photograph it except the pelicans.\n\nThe eastern coast has a different light from the south — harsher at midday, more golden at the edges of the day, more dramatic in the way it falls across the flat scrubland and the lagoon surface. Everything at Arugam Bay exists under this light: the surfboards lined up outside the guesthouses in the morning, the fishing boats crossing the lagoon mouth, the elephants grazing in the distance along the approach road at dusk. It is a light that makes ordinary things beautiful and beautiful things unforgettable.\n\nArugam Bay asks something of you — the long journey, the heat, the acceptance of limited infrastructure, the willingness to be in a place that operates on its own terms rather than yours. In return it gives you something that the more developed and accessible destinations cannot: the feeling of having genuinely arrived somewhere, of having crossed a distance that meant something, of being in a place where the ocean is doing what it has always done and you are fortunate enough to be in the water when it does it."
      }
    ]
  };

  return (
    <div className="space-y-20">
      <header className="mb-20 border-b border-[#5A5A40]/10 pb-12">
        <span className="text-[11px] uppercase tracking-[0.5em] text-[#5A5A40]/60 font-medium">Coastal Destination</span>
        <h1 className="text-5xl md:text-7xl font-light tracking-tighter mt-6 mb-6 text-[#2d2d2d]">{content.title}</h1>
        <h2 className="text-2xl font-light text-[#2d2d2d]/70">{content.subtitle}</h2>
        <p className="text-sm text-[#2d2d2d]/50 mt-4 max-w-xl">{content.description}</p>
      </header>
      
      <div className="space-y-20">
        {content.sections.map((section, index) => (
          <section key={index} className="grid md:grid-cols-[200px,1fr] gap-8">
            <h3 className="text-[11px] uppercase tracking-[0.3em] text-[#5A5A40]/50 pt-2">{section.title.split(':')[0]}</h3>
            <div className="space-y-4">
              <h4 className="text-2xl md:text-3xl font-semibold text-black">{section.title.split(':')[1]}</h4>
              <p className="text-[#2d2d2d]/80 leading-relaxed font-light whitespace-pre-line">{section.body}</p>
            </div>
          </section>
        ))}
      </div>
    </div>
  );
};

export default AboutArugamBay;
