import React from 'react';
import { Language } from '../types';

interface AboutMihintaleProps {
  language: Language;
}

const AboutMihintale: React.FC<AboutMihintaleProps> = ({ language }) => {
  const content = {
    title: language === 'EN' ? "Complete Travel Guide — Mihintale" : "සම්පූර්ණ සංචාරක මාර්ගෝපදේශය — මිහින්තලේ",
    subtitle: language === 'EN' ? "The Cradle of Buddhism in Sri Lanka — Where the Dhamma First Touched This Island" : "ශ්‍රී ලංකාවේ බුදුදහමේ තොටිල්ල — ධර්මය ප්‍රථමයෙන් මෙම දිවයිනට ස්පර්ශ වූ ස්ථානය",
    description: language === 'EN' ? "Anuradhapura District, North Central Province • UNESCO World Heritage environs • Open daily • 13 km from Anuradhapura" : "අනුරාධපුර දිස්ත්‍රික්කය, උතුරු මැද පළාත • යුනෙස්කෝ ලෝක උරුම පරිසරය • දිනපතා විවෘතයි • අනුරාධපුරයේ සිට කි.මී. 13 යි",
    sections: [
      {
        title: language === 'EN' ? "Section 01: Introduction — Why Mihintale Matters" : "01 වන කොටස: හැඳින්වීම — මිහින්තලේ වැදගත් වන්නේ ඇයි",
        body: "Mihintale is not simply an archaeological site. It is the place where, according to the ancient Pali chronicles that form the foundation of Sri Lanka's historical memory, Buddhism arrived on the island — the precise spot where the Indian monk Mahinda met the Sinhalese king Devanampiya Tissa in the third century BCE and delivered the teachings of the Buddha for the first time on Sri Lankan soil. For the 70 percent of Sri Lanka's population that identifies as Theravada Buddhist, this hillside in the north-central dry zone occupies a place in religious imagination and national identity that is without parallel. Mihintale is not merely old. It is, in the deepest sense available to a place, foundational.\n\nThe site rises from the flat scrubland of the Anuradhapura plain as a series of rocky granite outcrops — a small mountain complex, modest in absolute height but commanding in its presence above the surrounding lowland. Across these outcrops, across the summit plateau and the lower terraces and the surrounding jungle, an extraordinary complex of ancient Buddhist structures has been built, rebuilt, venerated, and tended for over two thousand years. Dagobas of brilliant white plaster, rock-cut refectories, ancient hospitals, meditation caves, and the summit stupa from which the view extends to the horizon in every direction — Mihintale holds more concentrated layers of living Buddhist history than almost any other site in the entire island.\n\nAnd yet, relative to the great sites of Anuradhapura just thirteen kilometres to the west, Mihintale receives a fraction of the international visitor attention. This is both inexplicable and fortunate. Inexplicable because the quality and significance of what is here is genuinely world-class. Fortunate because the comparative quiet of the site gives the visit a contemplative depth that is increasingly difficult to find at the more celebrated destinations of the Cultural Triangle. Mihintale is a place that rewards slowness, attention, and a genuine willingness to be moved by the weight of what happened here."
      },
      {
        title: language === 'EN' ? "Section 02: History — The Moment Buddhism Came to Sri Lanka" : "02 වන කොටස: ඉතිහාසය — බුදුදහම ශ්‍රී ලංකාවට පැමිණි මොහොත",
        body: "The founding story of Mihintale is one of the most consequential single encounters in the religious history of Asia. In approximately 247 BCE, during the reign of King Devanampiya Tissa of the ancient Sinhalese kingdom of Anuradhapura, a monk named Mahinda arrived at this hillside. Mahinda was the son — or in some accounts the close disciple — of the great Indian emperor Ashoka, who had embraced Buddhism after a devastating military campaign and become its most powerful royal patron in the ancient world. Ashoka dispatched missionaries to carry the Buddha's teachings to the neighbouring kingdoms, and Mahinda was sent to Lanka.\n\nThe encounter between Mahinda and the king, as recorded in the Mahavamsa — the great Pali chronicle of Sri Lanka composed in the 6th century CE — took place on this very hillside, where the king had come to hunt deer. Mahinda tested the king's intelligence and receptiveness with a famous riddle involving a mango tree, and satisfied with the answer, proceeded to preach the Dhamma. The king, his court, and eventually his entire kingdom embraced the teachings. This single encounter set in motion a religious and cultural transformation that shaped every subsequent aspect of Sinhalese civilisation — its art, its architecture, its literature, its political ideology, and its sense of national identity — and whose effects are visible and living in Sri Lanka to this day.\n\nThe site was developed as a major monastic complex almost immediately after this event. The earliest structures at Mihintale date to the 3rd century BCE, and construction and renovation continued through the Anuradhapura period and beyond, creating the layered archaeological landscape that visitors encounter today. The cave where Mahinda is believed to have meditated and spent his final years was venerated from the earliest period, and the various dagobas, pavilions, and terraces of the complex were built to honour both the historical events and the monks and rulers who maintained the tradition over the following centuries. Mihintale has been in continuous religious use for over two thousand years — a fact that gives every stone of the place a resonance that purely archaeological sites cannot achieve.\n\n\"At Mihintale, history and faith are the same thing — the encounter between Mahinda and the king was not merely recorded here, it is still happening, renewed by every pilgrim who climbs these steps.\""
      },
      {
        title: language === 'EN' ? "Section 03: The Ascent — 1,840 Steps to the Summit" : "03 වන කොටස: නැගීම — කඳු මුදුනට පියවර 1,840 ක්",
        body: "The approach to Mihintale's summit complex is made via a monumental granite staircase of 1,840 steps that rises from the base of the hill through three distinct levels of the ancient complex before reaching the summit plateau. This staircase is itself a work of considerable antiquity — portions of it date to the Anuradhapura period and the stone steps have been worn smooth by two millennia of pilgrims' feet into gentle curves and dips that are among the most tangible physical records of continuous human devotion available anywhere in Sri Lanka. Walking these steps is not simply an approach to the site — it is the site, or at least the beginning of it, and the rhythm of the ascent, the changing views as you gain height, and the succession of monuments and structures that appear at each level of the climb are as much a part of the Mihintale experience as anything at the summit.\n\nThe steps are broad and relatively shallow in the lower sections, becoming steeper and more demanding as the climb progresses. The first level of the complex — the Kantaka Cetiya level — is reached after a relatively modest climb and contains one of the site's most important structures. The middle section of the ascent passes through a shaded avenue of frangipani trees that fills the air with fragrance during the flowering season and provides welcome relief from the sun. The upper section is the most demanding, with taller and more closely spaced steps that require genuine physical effort in the heat. Most visitors manage the full ascent comfortably, though it is worth being honest with yourself about your fitness level before committing to the summit, particularly in the heat of midday.\n\nThe staircase is flanked at various points by lion statues, ancient lamp posts, and the remnants of structures that once lined the pilgrimage route. At the base, a large reclining lion — considerably damaged but still imposing — marks the formal beginning of the sacred precinct. Along the route, small shrines and offering places receive fresh flowers and incense from pilgrims throughout the day, and the smell of jasmine and frangipani that accompanies the climb is deeply characteristic of the Mihintale experience. Pilgrims typically ascend barefoot in accordance with the tradition of removing footwear at sacred sites — a practice that connects the modern visitor physically to the countless millions who have made this same climb over the preceding twenty-three centuries."
      },
      {
        title: language === 'EN' ? "Section 04: The Kantaka Cetiya — The Ancient Dagoba of the Lower Terrace" : "04 වන කොටස: කණ්ඨක චෛත්‍යය — පහළ මළුවේ පැරණි දාගැබ",
        body: "The Kantaka Cetiya is the oldest and in many ways the most archaeologically significant structure at Mihintale, and it is reached at the first major terrace of the ascent. Constructed in the 3rd or 2nd century BCE — making it among the oldest surviving dagobas in Sri Lanka — the Kantaka Cetiya is a large brick structure that has not been restored in the manner of the great white-plastered dagobas of Anuradhapura. Instead, it stands in a partially excavated state that reveals the original brick construction and the extraordinary quality of the sculptural decoration that once covered its four cardinal vahalkadas — the ornamental frontispieces that marked the four compass directions of the dagoba's base.\n\nThese vahalkadas are the glory of the Kantaka Cetiya and among the finest examples of early Sinhalese sculptural art in existence. Each frontispiece is decorated with intricate carvings of dwarfs, elephants, geese, and floral motifs arranged in registers of extraordinary precision and vitality. The quality of the carving — the expressiveness of the dwarf figures, the rhythmic energy of the elephant processions, the delicacy of the lotus borders — speaks to a mature and highly sophisticated sculptural tradition already fully developed by the earliest centuries of the common era. The fact that these carvings have been protected by their archaeological burial from the erosion and weathering that has damaged more exposed stonework means that they retain a crispness of detail that many much younger carvings have lost entirely.\n\nThe terrace around the Kantaka Cetiya contains the remnants of several other early structures — the foundations of image houses, the outlines of meditation platforms, and the traces of the paved paths that connected the various buildings of this level of the complex. Archaeologists have identified evidence of successive phases of construction and renovation spanning many centuries, and the visible remains represent only a fraction of what once stood here. Spending time at this terrace before continuing the ascent is strongly recommended — the Kantaka Cetiya's sculptural detail rewards close examination, and the atmosphere of the lower terrace, shaded by trees and relatively quiet even when the upper site is busier, has a particular meditative quality."
      },
      {
        title: language === 'EN' ? "Section 05: The Ambasthale Dagoba — Where the Meeting Happened" : "05 වන කොටස: අම්බස්තල දාගැබ — හමුවීම සිදුවූ ස්ථානය",
        body: "The Ambasthale Dagoba, situated on the middle terrace of the Mihintale complex, marks the precise spot — according to tradition — where the encounter between Mahinda and King Devanampiya Tissa took place. The name means \"mango tree place\" in Sinhala, a reference to the mango tree riddle with which Mahinda tested the king's intelligence before beginning his teaching. This dagoba is therefore not simply an ancient monument but a marker of the most theologically significant event in Sri Lankan history, and it is treated with a corresponding intensity of devotion by pilgrims who have come specifically to stand on the ground where the Dhamma first touched this island.\n\nThe dagoba itself is a beautifully proportioned white structure of moderate size, surrounded by a paved courtyard that is kept swept and clean by the resident monastic community. Pilgrims bring offerings of lotus flowers, jasmine, and frangipani, which are laid at the base of the structure and around the small shrine that marks the spot of the meeting. The fragrance of fresh flowers on a morning visit, combined with the sound of chanting from the nearby shrine rooms and the view over the surrounding jungle from the terrace, creates an atmosphere of devotional intensity that is genuinely moving regardless of the visitor's own religious tradition or lack of one. The sacred quality of a place is not dependent on shared belief — it is a function of the accumulated weight of human reverence, and that weight at the Ambasthale Dagoba is considerable.\n\nA large standing Buddha figure erected in relatively recent times faces the dagoba from one side of the courtyard, and the surrounding terrace contains the foundations of ancient structures and a number of carved stone elements that have been collected and displayed in the open air. The view from this terrace — over the flat Anuradhapura plain stretching to the west, with the great dagobas of the ancient capital visible in the distance on a clear day — is one of the most historically layered panoramas in Sri Lanka, encompassing in a single glance the landscape within which two thousand years of Sinhalese Buddhist civilisation has unfolded."
      },
      {
        title: language === 'EN' ? "Section 06: The Summit — Maha Seya and the View from the Top" : "06 වන කොටස: කඳු මුදුන — මහා සෑය සහ ඉහළින් බලන දසුන",
        body: "The final push to the summit of Mihintale brings you to the highest point of the rocky complex, where the Maha Seya dagoba — also known as the Mahinda Seya — sits in brilliant white isolation above the surrounding jungle and plain. The summit is reached via the steepest and most demanding section of the staircase, and the physical effort required for the final ascent means that the arrival at the top carries a sense of earned reward that amplifies the impact of what you find there. The dagoba, though not enormous by the standards of the great Anuradhapura structures, is perfectly proportioned and immaculately maintained, and its white plaster surface catches the light of the sky above it with an intensity that is almost luminous on a clear day.\n\nThe Maha Seya is said to enshrine a single hair relic of the Buddha, brought to Lanka by Mahinda and interred here as the founding sacred object of the hillside complex. Whether or not one approaches this claim from within a framework of religious faith, the idea of a structure that has been built and maintained and venerated for over two thousand years around a single sacred object — continuously, through the rise and fall of kingdoms and the passage of empires and the survival of two millennia of monsoons and earthquakes and human conflict — carries a weight that is entirely independent of belief. This is what continuity looks like when it is measured in centuries rather than years.\n\nThe view from the summit plateau is the finest available from anywhere in the Mihintale complex and one of the great panoramic views of the north-central province. The flat plain extends in every direction, broken only by the rocky outcrops of the Mihintale range and the distant glint of ancient irrigation tanks. To the west, on a clear day, the great white dome of the Ruwanwelisaya dagoba in Anuradhapura is visible above the treeline — a monument visible from forty kilometres away and a reminder of the extraordinary scale of ambition that characterised the builders of the ancient kingdom. Monks come to the summit terrace to meditate in the early morning, and the silence of the hilltop at dawn — before the heat builds and before the day's pilgrims begin to arrive — is among the most profound available anywhere in Sri Lanka."
      },
      {
        title: language === 'EN' ? "Section 07: Mahinda's Cave and the Meditation Retreats" : "07 වන කොටස: මිහිඳු ගුහාව සහ භාවනා ආරාම",
        body: "To the side of the main summit complex, accessible via a short path from the upper terrace, is the cave where the monk Mahinda is believed to have lived, meditated, and eventually died. The cave is a natural granite shelter enlarged and improved by human hands, and it has been a site of veneration since the earliest period of the complex's history. A small shrine inside the cave contains offerings and a simple altar, and the rock walls and ceiling of the shelter retain an atmosphere of extraordinary quietness — a quality of enclosure and protection that is very different from the open, airy exposure of the summit terraces above.\n\nAround the Mihintale complex, a number of other meditation caves and forest hermitages were developed over the centuries to serve the needs of the resident monastic community. These were not places of public worship but places of retreat — caves in the rocky hillside fitted with stone beds, water channels, and drip ledges carved above the cave mouths to divert rainwater away from the sleeping and meditation areas. The sophistication of these arrangements, and the number of such caves that survive across the Mihintale hills, speaks to a monastic community of considerable size and a tradition of forest meditation practice that was integral to the Theravada Buddhism of the Anuradhapura period.\n\nSeveral of these meditation caves are visible from the main paths of the complex, and some can be visited with a degree of scrambling over the rocky terrain. Their presence is a reminder that Mihintale was not simply a ceremonial centre — it was a living monastic community, home to hundreds of monks at the height of the Anuradhapura period, whose daily lives of meditation, study, and religious practice animated every structure on the hillside. The ruins of the refectory — the communal dining hall where the monks received their daily meal — are among the most impressive non-religious structures at the site, with enormous stone troughs that were used to receive the food offered by the lay community still standing in their original positions."
      },
      {
        title: language === 'EN' ? "Section 08: The Ancient Hospital — Medicine and Compassion" : "08 වන කොටස: පැරණි රෝහල — වෛද්‍ය විද්‍යාව සහ කරුණාව",
        body: "One of the most fascinating and least-discussed elements of the Mihintale complex is the ancient hospital that sits at the base of the hillside near the main entrance. This structure, excavated and partially restored by archaeologists, is one of the earliest known purpose-built hospitals in the world — a facility constructed to provide medical care to pilgrims visiting the sacred site and to the resident monastic community. Its existence reflects the Buddhist principle of compassion expressed in practical institutional form, and the sophistication of what has been found here suggests a medical tradition of considerable advancement for its period.\n\nThe most remarkable object associated with the Mihintale hospital is the large stone medicinal bath — a human-shaped trough carved from a single block of stone, large enough to contain a human body in a reclining position, which was used for medicated oil baths as part of the Ayurvedic treatment tradition. This object, unique of its kind in Sri Lanka and among the most remarkable surviving artifacts of ancient South Asian medicine, has been found to contain residues of the herbal oils used in treatment — a direct chemical trace of the healing practices conducted here over a thousand years ago. The bath is displayed near the hospital site and is often overlooked by visitors focused on the religious structures of the hillside above, which is a significant missed opportunity.\n\nThe hospital complex also includes the remains of a pharmacy, patient wards, and administrative buildings — a complete institutional structure that reflects the organisational capacity and the social values of the Anuradhapura kingdom at the height of its power. The provision of free medical care to the sick, funded by the state and organised through the religious institutions of the capital, represents a form of social welfare that was ahead of its time by many centuries, and the hospital at Mihintale is one of the most concrete surviving demonstrations of how this welfare system operated in practice. For visitors with an interest in the history of medicine or in the social history of ancient civilisations, the hospital at Mihintale is as interesting as anything at the more celebrated heritage sites of the Cultural Triangle."
      },
      {
        title: language === 'EN' ? "Section 09: The Poson Festival — Mihintale at Its Most Sacred" : "09 වන කොටස: පොසොන් උත්සවය — මිහින්තලයේ පූජනීයම අවස්ථාව",
        body: "Mihintale is a significant pilgrimage destination throughout the year, but it becomes the focus of the single most important pilgrimage in the Sri Lankan Buddhist calendar during the Poson full moon festival, which falls in June. Poson Poya commemorates the arrival of Buddhism in Sri Lanka — the very event that Mihintale marks — and the pilgrimage to the hillside on this night draws hundreds of thousands of devotees from across the island in one of the largest and most visually extraordinary religious gatherings in South Asia. The entire hillside is illuminated by oil lamps and electric lights, the staircase is lined with pilgrims ascending and descending throughout the night, and the sound of chanting and the smell of incense and flowers creates an atmosphere of collective devotion that has no parallel at any other time of the Sri Lankan religious calendar.\n\nFor travellers fortunate enough to be in Sri Lanka during Poson, a visit to Mihintale on the full moon night is an experience of the first order — an encounter with living Buddhist devotion at a scale and intensity that is genuinely overwhelming. The practical challenges of visiting on this night are considerable: the roads approaching Mihintale are closed to private vehicles several kilometres from the site, accommodation in the area is fully booked months in advance, and the crowds on the staircase are so dense that the ascent takes many times longer than on a normal day. None of this diminishes the experience, which most visitors who make the effort to be there describe as one of the most profound and memorable of their time in Sri Lanka. It is an experience that makes immediately and viscerally clear why Mihintale is not simply a heritage site but the living heart of a religious tradition that has been sustained on this island for twenty-three centuries.\n\nOutside of Poson, the site receives significant numbers of Sri Lankan pilgrims on every Poya day — the full moon day observed as a religious holiday each month — and the atmosphere on these days is considerably more devotionally charged than on ordinary weekdays. Visiting on a Poya day offers the chance to observe the site as it has functioned for millennia — as a place of active pilgrimage and worship rather than archaeological tourism — and the presence of white-clad pilgrims at the dagobas, the smell of incense, and the sound of chanting add a dimension that transforms the experience for visitors of any background."
      },
      {
        title: language === 'EN' ? "Section 10: Practical Information — What You Need to Know" : "10 වන කොටස: ප්‍රායෝගික තොරතුරු — ඔබ දැනගත යුතු දේ",
        body: "Location: 13 km from Anuradhapura\nOpening hours: 6:00 AM – 9:00 PM\nEntrance fee: USD 5–10 per person\nSteps to summit: 1,840 granite steps\nFrom Colombo: ~205 km (3.5–4 hrs)\nNearest hospital: Anuradhapura Teaching\n\nFootwear must be removed before ascending the staircase — this is a religious requirement enforced throughout the site, not merely a suggestion. The granite steps are worn smooth and can be slippery in wet weather, so exercise particular caution on the descent after rain. Shoe minders are available at the base of the steps for a small fee and are a worthwhile service, as walking the full distance back to where you parked in bare feet is less comfortable than it sounds. Appropriate dress is required throughout the complex — shoulders and knees should be covered, and tight or revealing clothing is not acceptable at this actively used sacred site.\n\nThe climb to the summit and back takes between two and three hours for most visitors moving at a comfortable pace with time to look properly at the major structures. Carrying water is essential — there are no facilities on the staircase itself and the climb in the heat of the day is genuinely demanding. Early morning is the optimal time for the visit on every count: the light is most favourable, the temperature is most comfortable, the crowds are thinnest, and the atmosphere of the site at dawn — when the monks are chanting and the oil lamps are still burning from the previous evening — is extraordinary.\n\nVisitor tips\nArrive at or before 7:00 AM. The difference between visiting Mihintale at dawn and at midday is the difference between a profound experience and an exhausting one. The early morning light on the white dagobas is beautiful, the air is cool, and the site belongs almost entirely to you and the pilgrims.\n\nDo not rush the Kantaka Cetiya. Most visitors pass through the lower terrace quickly on their way to the summit, missing the finest sculptural detail on the site. Spend at least twenty minutes examining the vahalkada carvings before continuing up.\n\nThe descent is harder on the knees than the ascent. Take your time coming down, particularly on the steeper upper sections, and use the handrails where available.\n\nPhotography is permitted throughout the site but should be conducted with sensitivity — do not photograph people at prayer without permission, and maintain a respectful distance from active devotional ceremonies."
      },
      {
        title: language === 'EN' ? "Section 11: Best Time to Visit — Season, Light, and the Pilgrimage Calendar" : "11 වන කොටස: සංචාරය කිරීමට හොඳම කාලය — කාලගුණය, ආලෝකය සහ වන්දනා දින දර්ශනය",
        body: "Mihintale is accessible year-round, and unlike the coastal destinations whose seasons are governed by the monsoon, the north-central province experiences a relatively stable climate through much of the year. The dry season in this region runs roughly from May through September, and during these months the heat can be intense — the Anuradhapura plain is one of the hottest parts of the island at midday and the open granite terraces of Mihintale amplify rather than moderate this heat. Visiting during the dry season is perfectly feasible provided you arrive early and plan to be off the exposed upper terraces before 10:00 AM.\n\nThe months of December through March, when the northeast monsoon has passed and the north-central province enjoys its most moderate temperatures and occasional refreshing cloud cover, are in many ways the most physically comfortable for visiting Mihintale. The light in these months has a quality that flattens somewhat in the haze of the dry season, and the slightly cooler air makes the ascent to the summit considerably less demanding. January and February in particular offer a good combination of manageable temperatures, clear skies, and the uncrowded conditions that follow the Christmas-New Year peak tourist period.\n\nThe most important consideration in timing a visit to Mihintale is the pilgrimage calendar rather than the weather calendar. Poson Poya in June is the single most significant date, as described above, and requires advance planning of a substantial kind if you wish to be present. All other Poya days are worth factoring into your planning — visiting on a full moon day brings the site to life in a way that is deeply rewarding, though it also means more people on the staircase and longer waits at the most popular shrines. For visitors seeking solitude and contemplative quiet, a weekday morning during the quieter tourist months of September through November offers the best combination of manageable conditions and minimal crowds."
      },
      {
        title: language === 'EN' ? "Section 12: Getting There — Reaching Mihintale" : "12 වන කොටස: ගමන් මාර්ගය — මිහින්තලයට ළඟා වීම",
        body: "Mihintale is located 13 kilometres east of Anuradhapura on the main A9 highway that runs northward from Colombo toward Jaffna, and this position on one of the island's principal arteries makes it straightforward to reach by a variety of means. The overwhelming majority of visitors to Mihintale arrive via Anuradhapura, which serves as the natural base for exploring the entire north-central heritage zone and which has its own extensive collection of ancient sites that together with Mihintale form a natural multi-day itinerary.\n\nFrom Anuradhapura, the journey to Mihintale takes approximately twenty minutes by tuk-tuk or private car along the flat and well-maintained A9. Buses also run regularly between Anuradhapura and Mihintale throughout the day, making the site accessible to travellers on a budget who are comfortable with the public transport system. The bus journey takes approximately thirty to forty minutes and deposits you at the base of the hill near the entrance. From Colombo, the journey to Mihintale is approximately 205 kilometres by road — around three and a half to four hours by private car using the North Central Expressway as far as it extends — or by train to Anuradhapura, from where onward transport to the site is straightforward.\n\nTravellers approaching from the Cultural Triangle — from Sigiriya, Dambulla, or Polonnaruwa — can reach Mihintale as part of a logical northward or southward circuit. From Sigiriya the drive to Mihintale takes approximately an hour and a half via Habarana and Kekirawa, passing through the flat scrubland of the dry zone interior. From Polonnaruwa the journey is slightly longer, and many travellers combine the two ancient cities in a two or three-day itinerary that also incorporates the Anuradhapura sacred city before moving on. Mihintale is best positioned as either the final stop before Anuradhapura on a southward journey or as a morning excursion from an Anuradhapura base during a longer Cultural Triangle circuit."
      },
      {
        title: language === 'EN' ? "Section 13: Nearby Attractions — Anuradhapura and the Sacred North" : "13 වන කොටස: අවට ආකර්ෂණීය ස්ථාන — අනුරාධපුරය සහ උතුරේ පිහිටි පූජනීය ස්ථාන",
        body: "Mihintale is most naturally paired with Anuradhapura, the ancient capital that sits thirteen kilometres to the west and which contains the most extensive collection of ancient Buddhist monuments in the entire island. Anuradhapura was the capital of the Sinhalese kingdom for over a thousand years and the centre of the Buddhist civilisation that Mihintale helped to establish. The scale of the ancient city — the colossal dagobas of the Ruwanwelisaya, Jetavanaramaya, and Abhayagiri that dominate the skyline, the ancient Sri Maha Bodhi tree grown from a cutting of the original Bodhi Tree in India under which the Buddha attained enlightenment, the palace terraces and bathing pools and monastic complexes that extend across an area of several square kilometres — is simply staggering, and a full day devoted to Anuradhapura is the natural complement to a morning at Mihintale.\n\nThe ancient city of Polonnaruwa, Sri Lanka's second great royal capital, is approximately 100 kilometres to the southeast and represents the natural next chapter in the historical narrative that Anuradhapura begins. Where Anuradhapura is vast and spread across a wide area that requires a bicycle or vehicle to navigate properly, Polonnaruwa is more compact and walkable, with its most remarkable monuments — the Gal Vihara rock temple with its four colossal Buddha figures, the Vatadage circular relic house, the royal palace complex — concentrated in a smaller area that can be thoroughly explored in a single extended morning. The two cities together provide the most complete available account of the Anuradhapura and Polonnaruwa periods of Sri Lankan history and are a natural pairing for any traveller with a serious interest in the island's heritage.\n\nFor those travelling northward from Mihintale toward Jaffna — the historic Tamil capital of the Northern Province that has become increasingly accessible to tourists since the end of the civil war — the road passes through a landscape of ancient tanks, dry-zone jungle, and scattered archaeological sites that are largely unexplored by the international visitor community. The Jaffna peninsula itself, with its distinctive Tamil Hindu culture, its Portuguese and Dutch colonial architecture, its extraordinary Nallur Kandaswamy Kovil, and its own deeply layered history of occupation and resistance, offers a completely different Sri Lanka from the Buddhist Cultural Triangle — and one that is increasingly recognised as among the most rewarding destinations on the island for travellers who make the effort to reach it."
      },
      {
        title: language === 'EN' ? "Section 14: Final Thoughts — The Weight of What Happened Here" : "14 වන කොටස: අවසාන අදහස් — මෙහි සිදුවූ දේහි වැදගත්කම",
        body: "There are sites in Sri Lanka that impress you with their scale, and sites that move you with their beauty, and sites that engage your historical imagination with the complexity of what took place within them. Mihintale is one of the rare places that does all three simultaneously — and then adds something further that very few sites anywhere in the world can offer: the sense of standing at a precise, documentable moment of beginning. Not the beginning of a building, or a dynasty, or a trade route, but the beginning of a civilisation's relationship with a system of thought and practice that has shaped every subsequent aspect of its existence for over two thousand years.\n\nThe steps worn smooth by the feet of pilgrims across twenty-three centuries are not a metaphor. They are a physical record, inscribed in stone, of the accumulated weight of human seeking — of the millions of people who have climbed this hill because something happened here that they wished to be close to, or to honour, or simply to feel in their own bodies the way that sacred ground feels different from ordinary ground. Whether or not you share the faith that motivates those pilgrims, the force of that accumulated seeking is palpable at Mihintale in a way that is available to anyone willing to move slowly and pay attention.\n\nClimb the steps in the early morning. Stand at the Ambasthale and look out over the plain that has been Buddhist land since before the common era began. Sit for a moment in the shade of the frangipani trees and let the sound of the chanting from the shrine room below carry up to you on the air. Mihintale does not need interpretation or amplification. It has been speaking for two thousand years, and it has not yet run out of things to say."
      }
    ]
  };

  return (
    <div className="space-y-20">
      <header className="mb-20 border-b border-[#5A5A40]/10 pb-12">
        <span className="text-[11px] uppercase tracking-[0.5em] text-[#5A5A40]/60 font-medium">Sacred Destination</span>
        <h1 className="text-5xl md:text-7xl font-light tracking-tighter mt-6 mb-6 text-[#2d2d2d]">{content.title}</h1>
        <h2 className="text-2xl font-light text-[#2d2d2d]/70">{content.subtitle}</h2>
        <p className="text-sm text-[#2d2d2d]/50 mt-4 max-w-xl">{content.description}</p>
      </header>
      
      <div className="space-y-20">
        {content.sections.map((section, index) => (
          <section key={index} className="grid md:grid-cols-[200px,1fr] gap-8">
            <h3 className="text-[11px] uppercase tracking-[0.3em] text-[#5A5A40]/50 pt-2">{section.title.split(':')[0]}</h3>
            <div className="space-y-4">
              <h4 className="text-2xl md:text-3xl font-semibold text-black">{section.title.split(':')[1]}</h4>
              <p className="text-[#2d2d2d]/80 leading-relaxed font-light whitespace-pre-line">{section.body}</p>
            </div>
          </section>
        ))}
      </div>
    </div>
  );
};

export default AboutMihintale;
